(()=>{const KEY="yeppoCRMv10IncomingStock";const modules=[
["Inicio","K-Beauty desde cero","8–10 min","Entender categorías, rutina y lenguaje básico."],
["Inicio","Cómo recomendar una rutina","10–12 min","Ordenar necesidades y armar una recomendación simple."],
["Especialista","Ingredientes que debes conocer","12–15 min","Reconocer ingredientes y comunicar sin promesas indebidas."],
["Negocio","Cómo vender más sin descontar","10 min","Subir ticket con rutina, complemento y asesoría."],
["Negocio","Cómo exhibir K-Beauty","8–10 min","Mejorar exhibición y navegación del surtido."],
["Negocio","Instagram, TikTok y WhatsApp para vender","12–15 min","Convertir contenido y conversación en venta."],
["Especialista","Cómo comprar y controlar stock","12 min","Comprar con rotación, cobertura y reposición."],
["Especialista","Venta responsable de cosméticos en Chile","10–12 min","Buenas prácticas comerciales y de comunicación."]
];let incoming=[];try{incoming=JSON.parse(localStorage.getItem(KEY)||"[]")}catch(e){}
const norm=s=>String(s||"").trim().toLowerCase();const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function excelDate(v){if(!v)return"";if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);if(typeof v==="number"){const d=new Date(Math.round((v-25569)*86400000));return isNaN(d)?"":d.toISOString().slice(0,10)}const d=new Date(v);return isNaN(d)?String(v).slice(0,10):d.toISOString().slice(0,10)}
function getCol(r,terms){for(const k of Object.keys(r)){const z=k.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");if(terms.some(t=>z.includes(t)))return r[k]}return""}
function alerts(){const out=[];for(const x of incoming){const sk=norm(x.sku);for(const [email,hist] of Object.entries(typeof SKU_HISTORY_90D!=="undefined"?SKU_HISTORY_90D:{})){const h=(hist||[]).find(y=>norm(y.sku)===sk);if(!h)continue;const c=(state?.clients||[]).find(z=>norm(z.email)===norm(email));if(!c)continue;const bc=typeof BC_STOCK_BY_SKU!=="undefined"?(BC_STOCK_BY_SKU[x.sku]?.stock??h.bc??0):(h.bc??0);out.push({client:c.cliente||c.contacto||email,id:c.id,email,sku:x.sku,product:x.product||h.product,qty:x.qty,eta:x.eta,orders:h.orders||0,units:h.units||0,bc})}}return out.sort((a,b)=>(a.eta||"9999").localeCompare(b.eta||"9999"))}
function renderIncoming(){const a=alerts(),k=document.getElementById("incomingKpis"),tb=document.getElementById("incomingRows");if(!k||!tb)return;k.innerHTML=[["SKU por llegar",incoming.length],["Unidades",incoming.reduce((s,x)=>s+(+x.qty||0),0)],["Alertas cliente",a.length],["Clientes únicos",new Set(a.map(x=>x.id)).size]].map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");tb.innerHTML=a.length?a.map(x=>`<tr data-client="${x.id}"><td><b>${esc(x.client)}</b><br><small>${esc(x.email)}</small></td><td><b>${esc(x.sku)}</b><br><small>${esc(x.product)}</small></td><td>${x.qty}</td><td>${x.eta||"Sin fecha"}</td><td>${x.orders} pedidos / ${x.units} u.</td><td><span class="v10badge ${x.bc>30?"now":"soon"}">${x.bc>30?"Disponible ahora":"Próximo ingreso"}</span><br><small>BC: ${x.bc}</small></td></tr>`).join(""):'<tr><td colspan="6">Carga un Excel para cruzar próximos ingresos con el historial de clientes.</td></tr>';tb.querySelectorAll("tr[data-client]").forEach(tr=>tr.onclick=()=>{const id=Number(tr.dataset.client);if(typeof openClient==="function")openClient(id);else{const c=(state.clients||[]).find(x=>x.id===id);if(c)alert(c.cliente)}})}
function addIncoming(){const tabs=document.querySelector(".tabs");if(!tabs||document.getElementById("incoming"))return;const btn=document.createElement("button");btn.className="tab";btn.dataset.tab="incoming";btn.textContent="Próximos ingresos";tabs.appendChild(btn);const sec=document.createElement("section");sec.id="incoming";sec.className="panel";sec.innerHTML=`<div class="topline"><div><h2>Radar de próximos ingresos</h2><p>Sube el Excel de mercadería por llegar. V10 reconoce SKU, cantidad y fecha estimada y lo cruza con clientes que compraron esos SKU.</p></div></div><div class="v10upload"><input id="incomingFile" type="file" accept=".xlsx,.xls"><button class="primary" id="incomingRead">Leer Excel</button><button class="soft" id="incomingClear">Limpiar ingresos</button><div id="incomingPreview" class="note">No se reemplaza el stock actual. Esta carga es una capa comercial separada.</div></div><div class="kpis" id="incomingKpis"></div><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>SKU / producto</th><th>Por llegar</th><th>Fecha estimada</th><th>Historial</th><th>Estado</th></tr></thead><tbody id="incomingRows"></tbody></table></div></section>`;document.querySelector("main")?.appendChild(sec)||tabs.parentNode.appendChild(sec);btn.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));btn.classList.add("active");sec.classList.add("active");renderIncoming()};document.getElementById("incomingRead").onclick=readExcel;document.getElementById("incomingClear").onclick=()=>{if(confirm("¿Limpiar la mercadería por llegar cargada?")){incoming=[];localStorage.removeItem(KEY);renderIncoming()}};renderIncoming()}
function readExcel(){const f=document.getElementById("incomingFile")?.files?.[0],pv=document.getElementById("incomingPreview");if(!f)return pv.textContent="Selecciona un Excel.";if(typeof XLSX==="undefined")return pv.textContent="El lector Excel no cargó. Recarga la página e intenta nuevamente.";const r=new FileReader();r.onload=()=>{try{const wb=XLSX.read(r.result,{type:"array",cellDates:true});let rows=[];for(const sh of wb.SheetNames){const x=XLSX.utils.sheet_to_json(wb.Sheets[sh],{defval:""});if(x.length){rows=x;break}}const mapped=rows.map((x,i)=>({sku:String(getCol(x,["sku","codigo","código"])).trim(),qty:+String(getCol(x,["cantidad","qty","unidades"])).replace(/[^0-9.-]/g,"")||0,eta:excelDate(getCol(x,["fecha estimada","fecha llegada","eta","llegada","arribo"])),product:String(getCol(x,["producto","nombre","descripcion","descripción"])).trim(),row:i+2})).filter(x=>x.sku);if(!mapped.length)throw Error("No encontré una columna SKU/Código.");const map=new Map(incoming.map(x=>[norm(x.sku),x]));mapped.forEach(x=>map.set(norm(x.sku),{...(map.get(norm(x.sku))||{}),...x,updatedAt:new Date().toISOString()}));incoming=[...map.values()];localStorage.setItem(KEY,JSON.stringify(incoming));pv.innerHTML=`<b>${mapped.length} SKU leídos</b> · ${mapped.reduce((s,x)=>s+x.qty,0)} unidades. Se cruzaron con el historial B2B.`;renderIncoming()}catch(e){pv.textContent="No pude leer el Excel: "+e.message}};r.readAsArrayBuffer(f)}
function addAcademy(){const sec=document.getElementById("academia");if(!sec||sec.dataset.v10academy)return;sec.dataset.v10academy="1";const wrap=document.createElement("div");wrap.className="academyV10";wrap.innerHTML='<div class="academyHead"><h2>Academia Yeppo B2B</h2><p>Contenido práctico para que el cliente venda mejor, compre mejor y aumente su recompra.</p></div><div class="academyGrid">'+modules.map((m,i)=>`<article><small>Módulo ${i+1} · ${m[0]}</small><h3>${m[1]}</h3><b>${m[2]}</b><p>${m[3]}</p><span>Video corto · resumen · ejercicio · mini quiz · acción comercial</span></article>`).join("")+'</div>';sec.prepend(wrap)}
function addTodayAlert(){const a=alerts();if(!a.length)return;const host=document.querySelector("#hoy .sales-hero")||document.getElementById("hoy");if(!host||document.getElementById("incomingToday"))return;const d=document.createElement("div");d.id="incomingToday";d.className="incomingToday";d.innerHTML=`<small>Radar próximos ingresos</small><b>${a.length} oportunidades por SKU en camino</b><span>${new Set(a.map(x=>x.id)).size} clientes históricos relacionados</span>`;d.onclick=()=>document.querySelector('[data-tab="incoming"]')?.click();host.appendChild(d)}
function init(){addAcademy();addIncoming();addTodayAlert()}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,50));else setTimeout(init,50);})();