const V11={version:"11.1-alpha",bcMinStock:30,b2bMinOrder:300000,academy:[["K-Beauty desde cero","Inicio"],["Cómo recomendar una rutina","Inicio"],["Ingredientes que debes conocer","Vendedor"],["Vender más sin descontar","Vendedor"],["Cómo exhibir K-Beauty","Especialista"],["Instagram, TikTok y WhatsApp","Especialista"],["Comprar y controlar stock","Negocio"],["Venta responsable de cosméticos","Negocio"]]};
const KEY="yeppoB2BV11State";
let state={clients:[],tasks:[],interactions:[],pipeline:[],imports:[],notes:"",recommendations:{},monthly:[],incoming:[],skuAlerts:[]};
function money(n){return new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(Number(n)||0)}
function el(id){return document.getElementById(id)}
async function load(){try{state={...state,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch(e){} if(!state.clients.length&&typeof loadV11Seed==="function"){const seed=await loadV11Seed();state.clients=seed.clients||[];state.recommendations=seed.recommendations||{};state.monthly=seed.monthly||[];state.seedMeta=seed.meta||{};save();}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function daysSince(d){if(!d)return null;return Math.floor((Date.now()-new Date(d).getTime())/86400000)}
function priority(c){const d=daysSince(c.lastPurchase);if(c.orders===1)return"P1";if(d!=null&&c.cycle&&d>c.cycle*1.25)return"P1";if(d!=null&&c.cycle&&d>c.cycle*.85)return"P2";return"P3"}
function renderKPIs(){const cs=state.clients, b2b=cs.filter(c=>c.isB2B),p1=b2b.filter(c=>priority(c)==="P1");el("kpis").innerHTML=[["Clientes",b2b.length],["P1 hoy",p1.length],["Tareas pendientes",state.tasks.filter(t=>!t.done).length],["Gestiones",state.interactions.length],["$ ganado",money(state.interactions.reduce((a,x)=>a+(+x.won||0),0))]].map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("")}
function renderClients(){const q=(el("search")?.value||"").toLowerCase();const rows=state.clients.filter(c=>c.isB2B&&(!q||JSON.stringify(c).toLowerCase().includes(q))).sort((a,b)=>priority(a).localeCompare(priority(b))).slice(0,500);el("clientRows").innerHTML=rows.map(c=>`<tr onclick="openClient('${c.id}')"><td><b>${esc(c.name)}</b><br><small>${esc(c.email||c.phone||"")}</small></td><td><span class="pill ${priority(c)}">${priority(c)}</span></td><td>${c.orders||0}</td><td>${c.lastPurchase||"—"}</td><td>${c.cycle?c.cycle+" días":"Sin patrón"}</td><td>${money(c.total||0)}</td><td>${esc(c.b2bReason||"Base B2B")}</td></tr>`).join("")}
function openClient(id){const c=state.clients.find(x=>x.id==id);if(!c)return;const recs=(state.recommendations||{})[(c.email||"").toLowerCase()]||[];const recHtml=recs.length?`<h3>Reposición sugerida · BC &gt; 30</h3><div class="recs">${recs.slice(0,6).map(r=>`<div><b>${esc(r.product)}</b><small>${esc(r.sku)} · BC ${r.bc} · ${r.orders} pedidos</small></div>`).join("")}</div>`:"<p>Sin historial SKU elegible para recomendación.</p>";el("clientPanel").classList.add("open");el("clientDetail").innerHTML=`<button class="close" onclick="el('clientPanel').classList.remove('open')">×</button><h2>${esc(c.name)}</h2><p><b>Prioridad:</b> ${priority(c)} · <b>Pedidos:</b> ${c.orders||0} · <b>Venta:</b> ${money(c.total||0)}</p><p><b>Última compra:</b> ${c.lastPurchase||"—"} · <b>Ciclo:</b> ${c.cycle?c.cycle+" días":"sin patrón suficiente"}</p><p><b>Señal B2B:</b> ${esc(c.b2bReason||"Base B2B")}</p><label>Resultado de contacto</label><select id="result"><option>Contactado</option><option>Respondió</option><option>Propuesta enviada</option><option>Pedido realizado</option><option>Sin respuesta</option></select><label>Monto ganado</label><input id="won" type="number" value="0"><label>Nota</label><textarea id="contactNote"></textarea><button onclick="registerContact('${c.id}')">Registrar gestión</button><button class="soft" onclick="prepareClientAI('${c.id}')">Preparar contacto IA</button><div id="clientAI" class="aiout"></div>${recHtml}` }
function registerContact(id){state.interactions.unshift({id:crypto.randomUUID(),clientId:id,date:new Date().toISOString(),result:el("result").value,won:+el("won").value||0,note:el("contactNote").value});save();renderAll();alert("Gestión registrada")}
function prepareClientAI(id){const c=state.clients.find(x=>x.id==id),p=priority(c),d=daysSince(c.lastPurchase);let why=p==="P1"?"prioridad alta":p==="P2"?"cerca de su recompra":"seguimiento preventivo";el("clientAI").textContent=`Objetivo: ${c.orders===1?"activar segunda compra":p==="P1"?"recompra/reactivación":"crecimiento"}. Motivo: ${why}${d!=null?", "+d+" días desde la última compra":""}.\n\nGuion: Hola, ¿cómo estás? Quería revisar cómo viene tu stock y qué productos te funcionaron mejor. Podemos preparar una reposición enfocada en rotación, evitando sobrecargar el pedido. ¿Te parece si lo vemos?`}
function renderFunnel(){const i=state.interactions;const n=k=>new Set(i.filter(x=>x.result===k).map(x=>x.clientId)).size;el("funnel").innerHTML=[["Contactados",new Set(i.map(x=>x.clientId)).size],["Respondieron",n("Respondió")],["Propuestas",n("Propuesta enviada")],["Pedidos",n("Pedido realizado")],["$ generado",money(i.reduce((a,x)=>a+(+x.won||0),0))]].map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("")}
function renderMonthly(){const box=el("monthly");if(!box)return;const rows=(state.monthly||[]).filter(x=>x.year===2026);box.innerHTML=rows.map(x=>`<div class="metric"><small>${x.monthName} ${x.period==="MTD"?"MTD":""}</small><b>${money(x.totalSales)}</b><span>${x.orders} pedidos</span></div>`).join("")}
function normalizeSku(v){return String(v||"").trim().toLowerCase()}
function excelDate(v){if(!v)return"";if(typeof v==="number"){const d=new Date(Math.round((v-25569)*86400*1000));return d.toISOString().slice(0,10)}const d=new Date(v);return isNaN(d)?String(v).slice(0,10):d.toISOString().slice(0,10)}
function readIncomingExcel(inp){const f=inp.files[0];if(!f)return;if(typeof XLSX==="undefined"){el("incomingPreview").textContent="No se pudo cargar el lector Excel.";return}const rd=new FileReader();rd.onload=()=>{try{const wb=XLSX.read(rd.result,{type:"array",cellDates:true});let rows=[];for(const sh of wb.SheetNames){const part=XLSX.utils.sheet_to_json(wb.Sheets[sh],{defval:""});if(part.length){rows=part;break}}const get=(r,terms)=>{for(const k of Object.keys(r)){const z=k.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");if(terms.some(t=>z.includes(t)))return r[k]}return""};const mapped=rows.map((r,i)=>({sku:String(get(r,["sku","codigo","código"])).trim(),qty:+String(get(r,["cantidad","qty","unidades","stock"])).replace(/[^0-9.-]/g,"")||0,eta:excelDate(get(r,["fecha estimada","fecha llegada","eta","llegada","arribo"])),product:String(get(r,["producto","nombre","descripcion","descripción"])).trim(),sourceRow:i+2})).filter(x=>x.sku);window.pendingIncoming=mapped;const dates=[...new Set(mapped.map(x=>x.eta).filter(Boolean))];el("incomingPreview").innerHTML=`<b>${mapped.length}</b> SKU detectados · <b>${mapped.reduce((a,x)=>a+x.qty,0)}</b> unidades · fechas: ${dates.slice(0,4).join(", ")||"sin fecha"}<br><button onclick="applyIncoming()">Aplicar próximos ingresos</button>`}catch(e){el("incomingPreview").textContent="No pude leer el Excel: "+e.message}};rd.readAsArrayBuffer(f)}
function buildIncomingAlerts(){const incoming=state.incoming||[], alerts=[];for(const inc of incoming){const sku=normalizeSku(inc.sku);for(const [email,recs] of Object.entries(state.recommendations||{})){const hit=(recs||[]).find(r=>normalizeSku(r.sku)===sku);if(hit){const c=state.clients.find(x=>(x.email||"").toLowerCase()===email);if(c)alerts.push({clientId:c.id,client:c.name,email,sku:inc.sku,product:inc.product||hit.product,qty:inc.qty,eta:inc.eta,previousOrders:hit.orders||0,bc:hit.bc||0,status:(hit.bc||0)>V11.bcMinStock?"Disponible ahora":"Próximo ingreso"})}}}state.skuAlerts=alerts}
function applyIncoming(){const rows=window.pendingIncoming||[];const m=new Map((state.incoming||[]).map(x=>[normalizeSku(x.sku),x]));rows.forEach(x=>m.set(normalizeSku(x.sku),{...(m.get(normalizeSku(x.sku))||{}),...x,updatedAt:new Date().toISOString()}));state.incoming=[...m.values()];state.imports.unshift({type:"incoming_stock",date:new Date().toISOString(),rows:rows.length});buildIncomingAlerts();save();renderIncoming();el("incomingPreview").textContent="Próximos ingresos aplicados y clientes cruzados con historial de compra."}
function renderIncoming(){const box=el("incomingAlerts");if(!box)return;const a=state.skuAlerts||[];const inc=state.incoming||[];el("incomingKpis").innerHTML=[["SKU por llegar",inc.length],["Unidades",inc.reduce((s,x)=>s+(+x.qty||0),0)],["Alertas cliente",a.length],["Clientes únicos",new Set(a.map(x=>x.clientId)).size]].map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");box.innerHTML=a.length?a.sort((x,y)=>(x.eta||"9999").localeCompare(y.eta||"9999")).slice(0,300).map(x=>`<tr onclick="openClient('${x.clientId}')"><td><b>${esc(x.client)}</b></td><td>${esc(x.sku)}<br><small>${esc(x.product||"")}</small></td><td>${x.qty}</td><td>${x.eta||"Sin fecha"}</td><td>${x.previousOrders}</td><td><span class="pill ${x.status==="Disponible ahora"?"P3":"P2"}">${x.status}</span></td></tr>`).join(""):`<tr><td colspan="6">Carga un Excel de mercadería entrante para detectar oportunidades.</td></tr>`}
function renderAcademy(){el("academy").innerHTML=V11.academy.map((m,i)=>`<article class="module"><small>MÓDULO ${i+1} · ${m[1]}</small><h3>${m[0]}</h3><p>Microlección + misión aplicada al negocio.</p><button onclick="alert('Selecciona un cliente desde Base maestra para asociar el seguimiento de Academia.')">Asignar</button></article>`).join("")}
function normalizeRow(r,idx){const g=(...ks)=>{for(const k of Object.keys(r)){if(ks.some(x=>k.toLowerCase().includes(x)))return r[k]}return""};const total=+(String(g("total","monto","venta")).replace(/[^0-9.-]/g,""))||0;const channel=String(g("canal","channel"));const tags=String(g("tag","etiqueta"));const reason=total>=V11.b2bMinOrder?"Pedido ≥ $300.000":/astro|b2b|mayor|por mayor/i.test(channel+" "+tags)?"Canal/etiqueta B2B":"Importado";return{id:String(g("id","cliente id","customer id")||"imp-"+idx+"-"+Date.now()),name:String(g("nombre","cliente","customer","name")||"Sin nombre"),email:String(g("email","correo")),phone:String(g("telefono","phone")),orders:+g("pedidos","orders")||1,lastPurchase:String(g("ultima compra","fecha","last purchase")).slice(0,10),cycle:+g("ciclo","recompra","cycle")||0,total,b2bReason:reason,isB2B:total>=V11.b2bMinOrder||/astro|b2b|mayor|por mayor/i.test(channel+" "+tags)||/b2b/i.test(reason)}}
function parseCSV(text){const lines=text.replace(/\r/g,"").split("\n").filter(Boolean),h=lines.shift().split(",").map(x=>x.trim());return lines.map(l=>{const v=l.match(/(".*?"|[^",]+)(?=\s*,|\s*$)/g)||[];return Object.fromEntries(h.map((k,i)=>[k,(v[i]||"").replace(/^"|"$/g,"").replace(/""/g,'"')]))})}
function previewImport(inp){const f=inp.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const raw=f.name.endsWith(".json")?JSON.parse(rd.result):parseCSV(rd.result);const rows=(Array.isArray(raw)?raw:raw.clients||[]).map(normalizeRow);window.pendingImport=rows;el("importPreview").innerHTML=`<b>${rows.length}</b> filas · <b>${rows.filter(x=>x.isB2B).length}</b> señales B2B <button onclick="applyImport()">Aplicar importación</button>`}catch(e){el("importPreview").textContent="No pude interpretar el archivo: "+e.message}};rd.readAsText(f)}
function applyImport(){const rows=window.pendingImport||[];const map=new Map(state.clients.map(c=>[c.id,c]));rows.forEach(c=>map.set(c.id,{...(map.get(c.id)||{}),...c}));state.clients=[...map.values()];state.imports.unshift({date:new Date().toISOString(),rows:rows.length});save();renderAll();el("importPreview").textContent="Importación aplicada. Historial manual conservado."}
function backup(){const b=new Blob([JSON.stringify({...state,version:V11.version,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="yeppo-b2b-v11-backup.json";a.click()}
function restore(inp){const f=inp.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...state,...JSON.parse(r.result)};save();renderAll();alert("Backup restaurado")}catch(e){alert("Backup inválido")}};r.readAsText(f)}
function renderAll(){if(state.incoming?.length&&!state.skuAlerts?.length)buildIncomingAlerts();renderKPIs();renderClients();renderFunnel();renderMonthly();renderIncoming();renderAcademy()}
document.addEventListener("DOMContentLoaded",async()=>{await load();renderAll()});