import Link from "next/link";
import {getAcademyData} from "@/lib/academy";
import {extractModules} from "@/lib/content-utils";
import {editorialCover} from "@/lib/editorial";

export const metadata={title:"Rutas de aprendizaje · Yeppo Academy"};
const routes=[
 {id:"kbeauty",title:"Entender K-Beauty",range:"Capítulos 1–3",goal:"Comprende el mercado y las razones por las que una tienda destaca.",first:"c01",numbers:[1,2,3],image:"/assets/editorial/chile-beauty.jpg"},
 {id:"piel",title:"Entender la piel",range:"Capítulos 4–9",goal:"Orienta una rutina y reconoce cuándo detener una recomendación.",first:"c04",numbers:[4,5,6,7,8,9],image:"/assets/editorial/chile-portrait.jpg"},
 {id:"productos",title:"Ingredientes y activos",range:"Capítulos 10–18",goal:"Lee fórmulas, compara ingredientes, entiende evidencia y combina activos con criterio.",first:"c10",numbers:[10,11,12,13,14,15,16,17,18],image:"/assets/editorial/yeppo-centella.jpg"},
 {id:"rutinas",title:"Productos y rutinas",range:"Capítulos 19–21",goal:"Distingue categorías, construye rutinas y aplica un algoritmo de recomendación.",first:"c19",numbers:[19,20,21],image:"/assets/editorial/chile-portrait.jpg"},
 {id:"venta",title:"Venta K-Beauty",range:"Capítulos 22–27",goal:"Entrevista, venta consultiva, explicación de producto, canasta, upselling y objeciones.",first:"c22",numbers:[22,23,24,25,26,27],image:"/assets/editorial/yeppo-store.jpg"},
 {id:"gestion",title:"Gestión del negocio",range:"Capítulos 28–35",goal:"Surtido, inventario, precio, promociones, merchandising, ecommerce y contenido.",first:"c28",numbers:[28,29,30,31,32,33,34,35],image:"/assets/editorial/yeppo-store.jpg"},
 {id:"journey",title:"Journey y recompra",range:"Capítulos 36–40",goal:"Diseña seguimiento, CRM, fidelización y métricas de retención.",first:"c36",numbers:[36,37,38,39,40],image:"/assets/editorial/chile-beauty.jpg"},
 {id:"partner",title:"Yeppo Partner B2B",range:"Capítulos 41–44",goal:"Compra mejor, construye pedidos y mejora la recompra mayorista.",first:"c41",numbers:[41,42,43,44],image:"/assets/editorial/yeppo-store.jpg"},
 {id:"seguridad",title:"Seguridad y regulación",range:"Capítulos 45–47",goal:"Opera con trazabilidad, regulación ISP y protocolos ante incidentes.",first:"c45",numbers:[45,46,47],image:"/assets/editorial/yeppo-centella.jpg"},
 {id:"certificacion",title:"Certificación",range:"Capítulos 48–50",goal:"Resuelve simulaciones integrales y demuestra competencias aplicadas.",first:"c48",numbers:[48,49,50],image:"/assets/editorial/chile-portrait.jpg"}
];
const chapterGoals={
 c01:["Inicial","Explicar K-Beauty sin reducirlo a una rutina de diez pasos."],c02:["Inicial","Leer el mercado chileno y distinguir interés de recompra."],c03:["Intermedio","Construir una ventaja de tienda basada en asesoría y selección."],
 c04:["Inicial","Relacionar funciones de la piel con beneficios cosméticos realistas."],c05:["Inicial","Distinguir tipo, estado y prioridad de la persona."],c06:["Intermedio","Ajustar una rutina cuando cambian tolerancia e hidratación."],
 c07:["Intermedio","Priorizar una preocupación sin saturar la rutina."],c08:["Intermedio","Reconocer el límite entre asesoría y diagnóstico."],c09:["Intermedio","Separar derivación profesional de una urgencia médica."],
 c10:["Intermedio","Leer INCI, etiqueta y reclamos de un cosmético."],c11:["Intermedio","Comparar humectantes, emolientes y oclusivos."],c12:["Intermedio","Distinguir tradición, evidencia y promesas sobre ingredientes."],
 c13:["Intermedio","Distinguir brillo, poros y brotes para orientar una rutina prudente."],c14:["Intermedio","Orientar el tono desigual con protección, tolerancia y expectativas claras."],c15:["Intermedio","Distinguir evidencia sólida, moderada y emergente en anti-aging."],c16:["Intermedio","Elegir exfoliación por objetivo, formulación y tolerancia."],c17:["Avanzado","Evaluar tendencias K-Beauty separando hype, vía y evidencia."],c18:["Avanzado","Combinar activos evitando reglas virales absolutas."],c19:["Intermedio","Distinguir categorías por función y no solo por formato."],c20:["Intermedio","Construir rutinas sostenibles por objetivo, estado y presupuesto."],c21:["Avanzado","Aplicar un algoritmo de recomendación sin diagnosticar."],c22:["Intermedio","Entrevistar al cliente con preguntas breves y útiles."],c23:["Intermedio","Vender de forma consultiva con escucha, priorización y seguimiento."],c24:["Intermedio","Explicar productos traduciendo técnica a beneficio y uso."],c25:["Intermedio","Construir canastas relevantes sin forzar la venta y medir su impacto."],c26:["Intermedio","Ofrecer upgrades con valor demostrable sin perder confianza."],c27:["Intermedio","Resolver objeciones con escucha, evidencia y respuestas consultivas."],c28:["Intermedio","Diseñar un surtido equilibrado por rol, demanda, margen y rotación."],c29:["Intermedio","Controlar cobertura, reposición y capital inmovilizado."],c30:["Intermedio","Fijar precios protegiendo margen y contribución por canal."],
 c31:["Intermedio","Diseñar promociones con objetivo, margen e incrementalidad."],c32:["Intermedio","Usar merchandising para orientar y aumentar productividad del espacio."],c33:["Intermedio","Convertir la asesoría en una experiencia ecommerce clara."],c34:["Intermedio","Crear contenido social con objetivo, prueba y medición."],c35:["Intermedio","Vender en video demostrando contexto de uso."],
 c36:["Intermedio","Mapear el viaje completo desde descubrimiento hasta recomendación."],c37:["Intermedio","Hacer seguimiento útil sin saturar."],c38:["Avanzado","Usar CRM para convertir datos en próximas acciones."],c39:["Avanzado","Diseñar retención y fidelización sin depender del descuento."],c40:["Avanzado","Gestionar el negocio con un tablero de métricas accionable."],
 c41:["Intermedio","Comprar mejor a Yeppo equilibrando variedad, profundidad y caja."],c42:["Intermedio","Navegar el catálogo Yeppo por necesidad y rol."],c43:["Avanzado","Construir un primer pedido que maximice aprendizaje y rotación."],c44:["Avanzado","Reponer según sell-through, cobertura y cadencia."],
 c45:["Avanzado","Aplicar fundamentos de regulación cosmética chilena."],c46:["Avanzado","Reducir riesgo de falsificación y mercado gris con trazabilidad."],c47:["Avanzado","Responder a reacciones adversas con protocolo y límites."],
 c48:["Certificación","Resolver casos de clientes con razonamiento y seguridad."],c49:["Certificación","Tomar decisiones integrales de surtido, stock, margen y CRM."],c50:["Certificación","Demostrar competencias finales de la ruta Yeppo Academy."]
};
export default async function Revision(){
 const data=await getAcademyData();
 const chapters=data.schools.flatMap(s=>s.chapters);
 const ready=chapters.filter(c=>c.n>=1&&c.n<=50),planned=[];
 return <main className="editorial-home"><div className="editorial-shell">
  <nav className="editorial-nav" aria-label="Navegación principal"><Link href="/revision" className="editorial-brand"><span>Y</span><b>YEPPO<small>ACADEMY · K-BEAUTY</small></b></Link><div><a href="#rutas">Rutas de aprendizaje</a><a href="#capitulos">Capítulos</a><Link href="/revision/c10">Ingredientes</Link><Link href="/revision/editar">Editar academia</Link></div></nav>
  <div className="editorial-first-screen"><section className="editorial-hero"><div className="editorial-hero-copy"><small>YEPPO ACADEMY</small><h1>Aprende K-Beauty. Recomienda mejor. <em>Haz crecer tu negocio.</em></h1><p>Formación práctica para equipos de venta, emprendedores y clientes B2B de belleza.</p><div className="editorial-hero-actions"><a href="#rutas" className="ya-btn editorial-white">Comenzar mi ruta <span aria-hidden="true">→</span></a><a href="#capitulos" className="editorial-text-link">Ver los {ready.length} capítulos →</a></div><div className="editorial-hero-benefits"><span>▣ Contenido práctico</span><span>◇ Casos reales</span><span>▥ Pensado para vender</span></div></div><div className="editorial-hero-photo"><img src="/assets/editorial/chile-model.jpg" alt="Retrato de belleza fotografiado en Santiago de Chile por Oss Leos"/><div className="editorial-hero-product"><img src="/assets/editorial/yeppo-centella.jpg" alt="Ampolla de centella del catálogo Yeppo"/><span>PRODUCTO EN YEPPO</span></div></div></section>
  <section className="editorial-routes" id="rutas"><div className="editorial-section-head"><div><h2>Elige tu ruta de aprendizaje</h2><p>Cada ruta combina contenido, casos y herramientas prácticas.</p></div></div><div className="editorial-routes-grid">{routes.map((r,i)=><article key={r.id} className={"editorial-route editorial-route-"+r.id}><small>{r.range}</small><h3>{r.title}</h3><p>{r.goal}</p><div className="editorial-route-image"><img src={r.image} alt={i===2?"Producto disponible en Yeppo":i===3?"Tienda Yeppo":"Fotografía editorial de belleza"}/>{r.first?<span className="editorial-route-arrow" aria-hidden="true">→</span>:<span>EN PREPARACIÓN</span>}</div>{r.first&&<a className="editorial-route-hit" href={"#"+r.id} aria-label={"Ver capítulos de "+r.title}/>}</article>)}</div></section></div>
  <div className="editorial-strip"><span>01 · Elige una ruta</span><span>02 · Aprende en módulos</span><span>03 · Aplica en tu negocio</span></div>
  <section className="editorial-infographic" aria-labelledby="metodo-yeppo"><div className="editorial-info-head"><small>UNA HERRAMIENTA PARA TU PRÓXIMA VENTA</small><h2 id="metodo-yeppo">El método Yeppo en una conversación</h2><p>Una recomendación concreta nace de la necesidad de la persona.</p></div><div className="editorial-info-flow"><article><span>01 / ESCUCHA</span><b>¿Qué usa hoy y qué quiere cambiar?</b><p>Identifica una prioridad y pregunta por sensibilidad o cambios recientes.</p></article><article><span>02 / SELECCIONA</span><b>Una rutina que sí podrá sostener</b><p>Parte por limpieza, hidratación y fotoprotección según el caso.</p></article><article><span>03 / EXPLICA</span><b>Qué esperar y cuándo revisar</b><p>Describe función, modo de uso y límites de la recomendación.</p></article></div><div className="editorial-info-foot"><strong>EN TIENDA</strong><span>Escuchar → elegir → explicar → acompañar</span><Link href="/revision/c03">Aplicarlo en una lección ↗</Link></div></section>
  <section className="editorial-feature"><div className="editorial-feature-photo"><img src="/assets/editorial/centella.jpg" alt="Hoja real de Centella asiatica"/><span>FOTOGRAFÍA BOTÁNICA REAL</span></div><div className="editorial-feature-copy"><small>HISTORIA DE UN INGREDIENTE</small><h2>¿Cómo llegó la centella asiática al cuidado de la piel?</h2><p>Conocida como gotu kola, tiene una larga historia de uso tradicional en distintas regiones de Asia. La investigación moderna estudia compuestos como asiaticósido y madecasósido. Aprende a distinguir historia, evidencia y promesas de marketing.</p><Link href="/revision/c12">Estudiar ingredientes calmantes →</Link><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/" target="_blank" rel="noopener noreferrer" className="editorial-source">Fuente científica ↗</a></div></section>
  <div className="editorial-courses" id="capitulos"><div className="editorial-section-head"><div><small>{ready.length} CAPÍTULOS DISPONIBLES</small><h2>Explora las lecciones</h2><p>Cada capítulo contiene ocho módulos de lectura y práctica.</p></div></div>{routes.filter(r=>ready.some(c=>r.numbers.includes(c.n))).map(r=><section className="editorial-course-group" id={r.id} key={r.id}><div className="editorial-group-head"><span>{r.range}</span><h3>{r.title}</h3><p>{r.goal}</p></div><div className="editorial-cards">{ready.filter(c=>r.numbers.includes(c.n)).map(c=><Link className="editorial-course" href={"/revision/"+c.id} key={c.id}><div className="editorial-course-photo"><img src={c.coverImage||editorialCover(c.id).src} alt={c.coverAlt||editorialCover(c.id).alt} loading="lazy"/><span>{String(c.n).padStart(2,"0")}</span></div><div className="editorial-course-body"><small>DISPONIBLE · {extractModules(c).length} MÓDULOS · ~{extractModules(c).length*7} MIN · {chapterGoals[c.id]?.[0]||"Inicial"}</small><h3>{c.title}</h3><p>{chapterGoals[c.id]?.[1]||c.summary}</p><b>Comenzar capítulo <span aria-hidden="true">→</span></b></div></Link>)}</div></section>)}</div>
  <section className="editorial-roadmap"><div><small>RUTA COMPLETA</small><h2>50 capítulos disponibles</h2><p>La academia completa ya está cargada: fundamentos, piel, ingredientes, rutinas, venta, gestión, journey, B2B, regulación y certificación.</p></div></section>
  <footer className="editorial-footer"><span>YEPPO ACADEMY</span><p>Aprender para recomendar con criterio.</p><a href="#rutas">Volver a las rutas ↑</a></footer>
 </div></main>
}
