import Link from "next/link";
import {getAcademyData} from "@/lib/academy";
import {extractModules} from "@/lib/content-utils";
import {editorialFor,editorialImage} from "@/lib/editorial";

export const metadata={title:"Academia K-Beauty · Yeppo"};

export default async function Revision(){
 const data=await getAcademyData();
 const chapters=data.schools.flatMap(s=>s.chapters);
 const ready=chapters.filter(c=>c.n<=12),planned=chapters.filter(c=>c.n>12);
 return <main className="editorial-home"><div className="editorial-shell">
   <nav className="editorial-nav" aria-label="Navegación principal"><Link href="/revision" className="editorial-brand"><span>Y</span><b>YEPPO<small>ACADEMIA K-BEAUTY</small></b></Link><div><a href="#capitulos">Capítulos</a><Link href="/revision/c10">Historias</Link><Link href="/login">Ingresar</Link></div></nav>
   <section className="editorial-hero"><div className="editorial-hero-copy"><small>YEPPO · ACADEMIA K-BEAUTY</small><h1>La belleza se aprende. <em>La confianza se construye.</em></h1><p>Una experiencia de formación para entender la piel, recomendar con criterio y hacer crecer tu negocio de belleza.</p><div className="editorial-hero-actions"><Link href="/revision/c01" className="ya-btn editorial-white">Comenzar a aprender <span aria-hidden="true">↗</span></Link><Link href="/revision/editar/c01" className="editorial-text-link">Editar borrador →</Link></div></div><div className="editorial-hero-photo"><img src="/assets/editorial/portrait.jpg" alt="Retrato fotográfico para la portada de la academia"/></div></section>
   <div className="editorial-strip"><span>01 · Conocimiento aplicable</span><span>02 · Consejos para vender mejor</span><span>03 · Fuentes y casos reales</span></div>
   <section className="editorial-intro"><div><small>APRENDER CON PROPÓSITO</small><h2>La piel es el punto de partida.<br/><em>La persona es el centro.</em></h2></div><p>Estudia a tu ritmo con lecciones completas, imágenes, historias de ingredientes y ejercicios para llevar cada idea a una conversación real con clientes.</p></section>
   <section className="editorial-feature"><div className="editorial-feature-photo"><img src="/assets/editorial/centella.jpg" alt="Hoja real de Centella asiatica"/><span>FOTOGRAFÍA BOTÁNICA REAL</span></div><div className="editorial-feature-copy"><small>UNA HISTORIA DETRÁS DE LA FÓRMULA</small><h2>¿Cómo llegó la centella asiática al cuidado de la piel?</h2><p>Conocida como gotu kola, esta planta tiene una larga historia de uso tradicional en distintas regiones de Asia. Su interés cosmético moderno llevó al estudio de compuestos como el asiaticósido y el madecasósido. En la academia aprenderás a distinguir historia, evidencia y promesas de marketing.</p><Link href="/revision/c10">Descubrir el capítulo de ingredientes →</Link><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/" target="_blank" rel="noopener noreferrer" className="editorial-source">Leer la revisión científica ↗</a></div></section>
   <section className="editorial-courses" id="capitulos"><div className="editorial-section-head"><div><small>TU RECORRIDO</small><h2>Explora los capítulos</h2><p>Contenido de revisión: 12 capítulos desarrollados. Entra en uno para leer sus módulos y probar las actividades.</p></div><Link href="/revision/editar/c01" className="ya-btn editorial-outline">Editar textos y videos ↗</Link></div><div className="editorial-cards">{ready.map(c=><Link className="editorial-course" href={"/revision/"+c.id} key={c.id}><div className={"editorial-course-photo"+(editorialFor(c.id).product?" editorial-product-photo":"")}><img src={editorialImage(c.id)} alt={editorialFor(c.id).alt} loading="lazy"/><span>{String(c.n).padStart(2,"0")}</span></div><div className="editorial-course-body"><small>{c.n<=7?"FUNDAMENTOS":"FORMACIÓN APLICADA"} · {extractModules(c).length} MÓDULOS</small><h3>{c.title}</h3><p>{editorialFor(c.id).story}</p><b>Explorar capítulo <span aria-hidden="true">→</span></b></div></Link>)}</div></section>
   <section className="editorial-roadmap"><div><small>LO QUE VIENE</small><h2>Una academia que sigue creciendo</h2><p>Los capítulos 13 al 50 están en planificación editorial. Su contenido aún se está desarrollando y verificando.</p></div><details><summary>Ver temario futuro ({planned.length} capítulos)</summary><div className="editorial-roadmap-grid">{planned.map(c=><div key={c.id}><small>{String(c.n).padStart(2,"0")}</small><span>{c.title}</span></div>)}</div></details></section>
   <footer className="editorial-footer"><span>YEPPO · ACADEMIA B2B</span><p>Conocimiento que se transforma en mejores conversaciones.</p><Link href="/login">Ingreso con cuenta →</Link></footer>
  </div></main>
}
