import Link from "next/link";
import {getAcademyData} from "@/lib/academy";
import {extractModules} from "@/lib/content-utils";
import {editorialFor,editorialImage} from "@/lib/editorial";

export const metadata={title:"Rutas de aprendizaje · Yeppo Academy"};
const routes=[
 {id:"kbeauty",title:"Entender K-Beauty",range:"Capítulos 1–3",goal:"Comprende el mercado y las razones por las que una tienda destaca.",first:"c01",numbers:[1,2,3],image:"/assets/editorial/chile-beauty.jpg"},
 {id:"piel",title:"Entender la piel",range:"Capítulos 4–9",goal:"Orienta una rutina y reconoce cuándo detener una recomendación.",first:"c04",numbers:[4,5,6,7,8,9],image:"/assets/editorial/chile-portrait.jpg"},
 {id:"productos",title:"Entender productos",range:"Capítulos 10–20",goal:"Lee fórmulas, compara ingredientes y construye rutinas.",first:"c10",numbers:[10,11,12],image:"/assets/editorial/yeppo-centella.jpg"},
 {id:"negocio",title:"Hacer crecer tu negocio",range:"Capítulos 21–50",goal:"Venta, surtido, margen, CRM y recompra B2B.",first:null,numbers:[],image:"/assets/editorial/yeppo-store.jpg"}
];
export default async function Revision(){
 const data=await getAcademyData();
 const chapters=data.schools.flatMap(s=>s.chapters);
 const ready=chapters.filter(c=>c.n<=12),planned=chapters.filter(c=>c.n>12);
 return <main className="editorial-home"><div className="editorial-shell">
  <nav className="editorial-nav" aria-label="Navegación principal"><Link href="/revision" className="editorial-brand"><span>Y</span><b>YEPPO<small>ACADEMY · K-BEAUTY</small></b></Link><div><a href="#rutas">Rutas</a><a href="#capitulos">Capítulos</a><Link href="/revision/c10">Ingredientes</Link></div></nav>
  <div className="editorial-first-screen"><section className="editorial-hero"><div className="editorial-hero-copy"><small>YEPPO ACADEMY · FORMACIÓN K-BEAUTY</small><h1>Aprende K-Beauty. Recomienda mejor. <em>Haz crecer tu negocio.</em></h1><p>Formación práctica para equipos de venta, emprendedores y clientes B2B de belleza.</p><div className="editorial-hero-actions"><a href="#rutas" className="ya-btn editorial-white">Explorar las rutas <span aria-hidden="true">↗</span></a><a href="#capitulos" className="editorial-text-link">Ver los 12 capítulos →</a></div></div><div className="editorial-hero-photo"><img src="/assets/editorial/chile-model.jpg" alt="Retrato de belleza fotografiado en Santiago de Chile por Oss Leos"/><div className="editorial-hero-product"><img src="/assets/editorial/yeppo-centella.jpg" alt="Ampolla de centella del catálogo Yeppo"/><span>PRODUCTOS EN YEPPO</span></div></div></section>
  <section className="editorial-routes" id="rutas"><div className="editorial-section-head"><div><small>ELIGE TU PUNTO DE PARTIDA</small><h2>Tu ruta de aprendizaje</h2><p>Puedes empezar por fundamentos o ir directo al tema que necesitas hoy.</p></div></div><div className="editorial-routes-grid">{routes.map((r,i)=><article key={r.id} className={"editorial-route editorial-route-"+r.id}><div className="editorial-route-head"><span className="editorial-route-number">0{i+1}</span><img src={r.image} alt={i===2?"Producto disponible en Yeppo":i===3?"Tienda Yeppo":"Fotografía editorial de belleza"}/></div><small>{r.range} · {r.first?`${r.numbers.length} disponibles`:"PRÓXIMAMENTE"}</small><h3>{r.title}</h3><p>{r.goal}</p>{r.first?<a href={"#"+r.id}>Ver capítulos de la ruta →</a>:<span className="editorial-route-pending">Contenido en desarrollo</span>}</article>)}</div></section></div>
  <div className="editorial-strip"><span>01 · Elige una ruta</span><span>02 · Aprende en módulos</span><span>03 · Aplica en tu negocio</span></div>
  <section className="editorial-infographic" aria-labelledby="metodo-yeppo"><div className="editorial-info-head"><small>UNA HERRAMIENTA PARA TU PRÓXIMA VENTA</small><h2 id="metodo-yeppo">El método Yeppo en una conversación</h2><p>Una recomendación concreta nace de la necesidad de la persona.</p></div><div className="editorial-info-flow"><article><span>01 / ESCUCHA</span><b>¿Qué usa hoy y qué quiere cambiar?</b><p>Identifica una prioridad y pregunta por sensibilidad o cambios recientes.</p></article><article><span>02 / SELECCIONA</span><b>Una rutina que sí podrá sostener</b><p>Parte por limpieza, hidratación y fotoprotección según el caso.</p></article><article><span>03 / EXPLICA</span><b>Qué esperar y cuándo revisar</b><p>Describe función, modo de uso y límites de la recomendación.</p></article></div><div className="editorial-info-foot"><strong>EN TIENDA</strong><span>Escuchar → elegir → explicar → acompañar</span><Link href="/revision/c03">Aplicarlo en una lección ↗</Link></div></section>
  <section className="editorial-feature"><div className="editorial-feature-photo"><img src="/assets/editorial/centella.jpg" alt="Hoja real de Centella asiatica"/><span>FOTOGRAFÍA BOTÁNICA REAL</span></div><div className="editorial-feature-copy"><small>HISTORIA DE UN INGREDIENTE</small><h2>¿Cómo llegó la centella asiática al cuidado de la piel?</h2><p>Conocida como gotu kola, tiene una larga historia de uso tradicional en distintas regiones de Asia. La investigación moderna estudia compuestos como asiaticósido y madecasósido. Aprende a distinguir historia, evidencia y promesas de marketing.</p><Link href="/revision/c12">Estudiar ingredientes calmantes →</Link><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/" target="_blank" rel="noopener noreferrer" className="editorial-source">Fuente científica ↗</a></div></section>
  <div className="editorial-courses" id="capitulos"><div className="editorial-section-head"><div><small>12 CAPÍTULOS DISPONIBLES</small><h2>Explora las lecciones</h2><p>Todos los capítulos publicados para esta revisión incluyen ocho módulos de lectura y práctica.</p></div></div>{routes.slice(0,3).map(r=><section className="editorial-course-group" id={r.id} key={r.id}><div className="editorial-group-head"><span>{r.range}</span><h3>{r.title}</h3><p>{r.goal}</p></div><div className="editorial-cards">{ready.filter(c=>r.numbers.includes(c.n)).map(c=><Link className="editorial-course" href={"/revision/"+c.id} key={c.id}><div className={"editorial-course-photo"+(editorialFor(c.id).product?" editorial-product-photo":"")}><img src={editorialImage(c.id)} alt={editorialFor(c.id).alt} loading="lazy"/><span>{String(c.n).padStart(2,"0")}</span></div><div className="editorial-course-body"><small>DISPONIBLE · {extractModules(c).length} MÓDULOS · ~{extractModules(c).length*7} MIN</small><h3>{c.title}</h3><p>{c.summary}</p><b>Comenzar capítulo <span aria-hidden="true">→</span></b></div></Link>)}</div></section>)}</div>
  <section className="editorial-roadmap"><div><small>PRÓXIMAMENTE</small><h2>Una academia que sigue creciendo</h2><p>Los capítulos 13 al 50 están planificados. Los incorporaremos cuando el contenido y sus fuentes estén verificados.</p></div><details><summary>Ver temario futuro ({planned.length} capítulos)</summary><div className="editorial-roadmap-grid">{planned.map(c=><div key={c.id}><small>{String(c.n).padStart(2,"0")}</small><span>{c.title}</span></div>)}</div></details></section>
  <footer className="editorial-footer"><span>YEPPO ACADEMY</span><p>Aprender para recomendar con criterio.</p><a href="#rutas">Volver a las rutas ↑</a></footer>
 </div></main>
}
