const maps={
 c01:{title:"K-Beauty: tres ideas que sí sirven en tienda",items:[["01","Filosofía","Cuidado constante y elecciones adaptadas a la persona."],["02","Fórmula","Importan el producto terminado, la textura y la tolerancia."],["03","Conversación","Explica un beneficio concreto sin prometer resultados universales."]],note:"En Yeppo: usa la historia de una marca para abrir la conversación; la recomendación se decide con la persona."},
 c02:{title:"Del interés por K-Beauty a una recompra responsable",items:[["01","Interés","La tendencia invita a preguntar, no demuestra que un producto sirva para todos."],["02","Elección","Relaciona necesidad, fórmula, textura, presupuesto y disponibilidad."],["03","Seguimiento","Explica uso y revisa tolerancia antes de ampliar la rutina."]],note:"Un dato de mercado describe un periodo y una fuente; no equivale a ventas de Yeppo ni garantiza demanda futura."},
 c03:{title:"La ventaja Yeppo se construye en cada paso",items:[["01","Descubrimiento","Agrupa opciones por necesidad y ayuda a encontrar."],["02","Asesoría","Pregunta, compara y explica por qué elegir."],["03","Recompra","Acompaña la experiencia y ajusta según tolerancia."]],note:"Ejercicio: elige un producto de Yeppo y escribe qué necesidad atiende, para quién sería cómodo y cuándo revisar."},
 c04:{title:"Piel: funciones que ayudan a explicar una rutina",items:[["01","Superficie","El estrato córneo reúne células y lípidos que participan en la barrera."],["02","Agua","La hidratación depende de retención de agua y pérdida hacia el ambiente."],["03","Límite","Un cosmético se explica por su función demostrada, sin atribuirle un diagnóstico."]],note:"Relaciona una función cutánea con una decisión de producto y comprueba el alcance del reclamo."},
 c05:{title:"Tipo, estado y preocupación son preguntas distintas",items:[["TIPO","Habitual","Cómo tiende a comportarse la piel a lo largo del tiempo."],["ESTADO","Hoy","Tirantez, confort o tolerancia que puede variar con la rutina y el ambiente."],["META","Prioridad","Qué desea mejorar la persona y cómo evaluará si le sirve."]],note:"El brillo y la tirantez pueden coexistir: pregunta por ambos antes de elegir textura."},
 c06:{title:"Cuando la tolerancia cambia, simplifica",items:[["01","Observar","Pregunta qué cambió en productos, frecuencia y ambiente."],["02","Reducir","Introduce menos variables y elige una rutina tolerable."],["03","Derivar","Ardor persistente, hinchazón o empeoramiento requieren evaluación."]],note:"La incomodidad no se interpreta automáticamente como adaptación ni como diagnóstico."},
 c07:{title:"Una prioridad permite una recomendación más clara",items:[["01","Escuchar","Distingue brotes, tono, textura, poros o luminosidad según lo que cuenta la persona."],["02","Priorizar","Elige una meta principal y revisa productos que ya usa."],["03","Revisar","Explica uso, tolerancia y cuándo volver a conversar."]],note:"No prometas corregir varias preocupaciones con un solo ingrediente sin evidencia del producto."},
 c08:{title:"El alcance de una conversación en tienda",items:[["SÍ","Observar","Preguntar por la rutina y describir lo que la persona relata."],["LÍMITE","No diagnosticar","No confirmar alergia, rosácea, dermatitis ni la causa de una lesión."],["ACCIÓN","Derivar","Ante lesiones que cambian, dolor o reacciones importantes, suspender la recomendación específica."]],note:"Un límite comunicado con calma protege a la persona y fortalece la confianza en Yeppo."},
 c09:{title:"Señal roja y emergencia requieren respuestas distintas",items:[["ROJO","Detener y derivar","Dolor intenso, hinchazón, ampollas o empeoramiento: no recomendar más cosméticos; orientar evaluación profesional."],["URGENTE","Atención inmediata","Dificultad respiratoria o compromiso general: buscar atención médica urgente."],["YEPPO","Acompañar con calma","Escuchar, explicar el límite de la asesoría y evitar diagnósticos o promesas."]],note:"Esta guía orienta la atención en tienda. Ante una situación médica, actúa según los protocolos locales de emergencia."},
 c10:{title:"Leer un cosmético en cuatro niveles",items:[["01","Etiqueta","Identifica uso, advertencias, lote, responsable y rotulación vigente."],["02","INCI","Reconoce ingredientes sin inferir porcentajes exactos de la lista."],["03","Fórmula","Considera textura, sistema completo y evidencia del producto."],["04","Consejo","Traduce la función al lenguaje de la clienta sin prometer curación."]],note:"Historia tradicional, ensayo de laboratorio y resultado clínico son niveles diferentes de evidencia."},
 c11:{title:"Una hidratante trabaja de varias maneras",items:[["01","Humectantes","Atraen y retienen agua en la capa superficial."],["02","Emolientes","Suavizan la superficie y mejoran la sensación."],["03","Oclusivos","Ayudan a reducir la pérdida de agua."]],note:"En Yeppo: compara la fórmula completa y la textura que la persona realmente usará; un ingrediente solo no define el resultado."},
 c12:{title:"Calmar: de la etiqueta a la experiencia",items:[["01","Escuchar","Pregunta qué cambió, qué siente y qué tolera."],["02","Leer","Distingue ingrediente destacado, INCI y fórmula completa."],["03","Acompañar","Simplifica, observa tolerancia y deriva ante señales intensas."]],note:"Centella y pantenol pueden orientar una elección cosmética; no sustituyen diagnóstico ni atención médica."},
 c13:{title:"Brillo, poros y brotes: tres decisiones diferentes",items:[["BRILLO","Confort y textura","Revisa limpieza suave e hidratación antes de sumar un activo."],["POROS","Apariencia visible","Evalúa congestión y tolerancia; no prometas cerrarlos."],["BROTES","Límite cosmético","Pregunta por duración y molestias; lesiones profundas o dolorosas requieren dermatología."]],note:"En Yeppo: distingue objetivo cosmético de tratamiento médico y explica el papel de cada producto en la rutina."},
 c14:{title:"Una ruta para el tono desigual",items:[["01","Escuchar","¿Marca tras un brote, tono apagado o lesión nueva que cambia?"],["02","Proteger","Revisa fotoprotección, productos irritantes y constancia."],["03","Elegir","Compara una fórmula por etiqueta, textura y uso; deriva cuando corresponda."]],note:"El objetivo es una recomendación cosmética clara. Melasma o manchas cambiantes requieren evaluación profesional."},
 c15:{title:"Anti-aging con criterio: prevenir, tratar y no sobreprometer",items:[["01","Base","Fotoprotección e hidratación sostienen cualquier estrategia."],["02","Prioridad","Elige el signo principal: líneas, textura, tono o firmeza visual."],["03","Evidencia","Compara molécula, formulación, vía de uso y calidad del estudio."],["04","Tolerancia","Un activo constante vale más que una rutina intensa que se abandona."]],note:"En Yeppo: no vendas edad ni miedo. Traduce evidencia a una expectativa concreta y revisable."}
};
export const chapterMapFor=id=>maps[id]||null;
export default function ChapterMap({id,override}){
 const map=override||maps[id];if(!map)return null;
 return <aside className="yeppo-chapter-map" aria-label={"Infografía Yeppo: "+map.title}><small>INFOGRAFÍA / YEPPO ACADEMY</small><h3>{map.title}</h3><div className="yeppo-chapter-map-grid">{map.items.map(([n,title,body])=><article key={n}><b>{n}</b><strong>{title}</strong><p>{body}</p></article>)}</div><p>{map.note}</p></aside>;
}
