const maps={
 c01:{title:"K-Beauty: tres ideas que sí sirven en tienda",items:[["01","Filosofía","Cuidado constante y elecciones adaptadas a la persona."],["02","Fórmula","Importan el producto terminado, la textura y la tolerancia."],["03","Conversación","Explica un beneficio concreto sin prometer resultados universales."]],note:"En Yeppo: usa la historia de una marca para abrir la conversación; la recomendación se decide con la persona."},
 c03:{title:"La ventaja Yeppo se construye en cada paso",items:[["01","Descubrimiento","Agrupa opciones por necesidad y ayuda a encontrar."],["02","Asesoría","Pregunta, compara y explica por qué elegir."],["03","Recompra","Acompaña la experiencia y ajusta según tolerancia."]],note:"Ejercicio: elige un producto de Yeppo y escribe qué necesidad atiende, para quién sería cómodo y cuándo revisar."},
 c09:{title:"Señal roja y emergencia requieren respuestas distintas",items:[["ROJO","Detener y derivar","Dolor intenso, hinchazón, ampollas o empeoramiento: no recomendar más cosméticos; orientar evaluación profesional."],["URGENTE","Atención inmediata","Dificultad respiratoria o compromiso general: buscar atención médica urgente."],["YEPPO","Acompañar con calma","Escuchar, explicar el límite de la asesoría y evitar diagnósticos o promesas."]],note:"Esta guía orienta la atención en tienda. Ante una situación médica, actúa según los protocolos locales de emergencia."},
 c11:{title:"Una hidratante trabaja de varias maneras",items:[["01","Humectantes","Atraen y retienen agua en la capa superficial."],["02","Emolientes","Suavizan la superficie y mejoran la sensación."],["03","Oclusivos","Ayudan a reducir la pérdida de agua."]],note:"En Yeppo: compara la fórmula completa y la textura que la persona realmente usará; un ingrediente solo no define el resultado."},
 c12:{title:"Calmar: de la etiqueta a la experiencia",items:[["01","Escuchar","Pregunta qué cambió, qué siente y qué tolera."],["02","Leer","Distingue ingrediente destacado, INCI y fórmula completa."],["03","Acompañar","Simplifica, observa tolerancia y deriva ante señales intensas."]],note:"Centella y pantenol pueden orientar una elección cosmética; no sustituyen diagnóstico ni atención médica."}
};
export default function ChapterMap({id}){
 const map=maps[id];if(!map)return null;
 return <aside className="yeppo-chapter-map" aria-label={"Infografía Yeppo: "+map.title}><small>INFOGRAFÍA / YEPPO ACADEMY</small><h3>{map.title}</h3><div className="yeppo-chapter-map-grid">{map.items.map(([n,title,body])=><article key={n}><b>{n}</b><strong>{title}</strong><p>{body}</p></article>)}</div><p>{map.note}</p></aside>;
}
