"use client";
import {useState} from "react";
const cases={
 c01:{prompt:"Una clienta pide una rutina coreana de diez pasos para empezar. ¿Qué le propones?",choices:["Diez productos para vivir la experiencia completa.","Preguntar por su rutina actual y construir pocos pasos sostenibles.","Un activo fuerte sin preguntar qué usa."],correct:1,reason:"K-Beauty no exige un número de pasos. La rutina debe responder a una necesidad y a la tolerancia de la persona."},
 c02:{prompt:"Un producto se vuelve viral. ¿Qué verifica Yeppo antes de recomendarlo?",choices:["Solo cuántas vistas tuvo.","Necesidad, disponibilidad, fórmula y encaje en una rutina.","Que la competencia ya lo vende."],correct:1,reason:"La demanda inicial puede ser una señal, pero una venta que se sostiene necesita selección, explicación y reposición."},
 c03:{prompt:"Una clienta compara dos tiendas con el mismo producto. ¿Qué agrega valor?",choices:["Prometer que funcionará para todos.","Explicar textura, uso y elección según la necesidad.","Ocultar la comparación."],correct:1,reason:"La asesoría útil convierte un catálogo compartido en una decisión clara para esa persona."},
 c04:{prompt:"Una clienta pregunta si un sérum puede cambiar la estructura de su dermis. ¿Qué explicas?",choices:["Que cualquier sérum llega a todas las capas.","Que una promesa cosmética debe corresponder al producto y su evidencia.","Que la dermis no tiene ninguna función."],correct:1,reason:"Conocer las capas de la piel permite explicar beneficios cosméticos sin extenderlos a efectos clínicos no demostrados."},
 c05:{prompt:"Una clienta tiene brillo en la zona T y tirantez tras lavarse. ¿Qué preguntas primero?",choices:["Qué usa para limpiar y cómo suele sentirse su piel.","Qué diagnóstico médico tiene.","Si quiere eliminar todo el sebo."],correct:0,reason:"Tipo habitual y estado actual pueden coexistir. La limpieza reciente y la sensación de tirantez ayudan a elegir una textura tolerable."},
 c06:{prompt:"Una clienta comenzó tres activos nuevos y ahora siente ardor. ¿Cómo orientas?",choices:["Agregar un exfoliante más fuerte.","Simplificar y revisar lo que cambió; derivar si persiste o empeora.","Afirmar que es una purga normal."],correct:1,reason:"Reducir variables facilita evaluar tolerancia; el ardor persistente o intenso sale del alcance de una recomendación rutinaria."},
 c07:{prompt:"Una clienta consulta por marcas, textura y brillo a la vez. ¿Cuál es el primer paso?",choices:["Vender un producto por cada preocupación.","Elegir una prioridad y revisar su rutina actual.","Prometer que todo desaparecerá esta semana."],correct:1,reason:"Priorizar permite explicar un objetivo observable sin saturar la rutina ni prometer resultados."},
 c08:{prompt:"Una persona pregunta si una rojez visible es rosácea. ¿Qué puedes responder?",choices:["Confirmar el diagnóstico mirando la piel.","Describir lo observado, preguntar por cambios y derivar si corresponde.","Descartar cualquier preocupación médica."],correct:1,reason:"La asesoría de venta no diagnostica. Puede reconocer límites, orientar una compra prudente y recomendar evaluación profesional."},
 c09:{prompt:"Una persona presenta hinchazón facial y dificultad para respirar tras usar un cosmético. ¿Qué haces?",choices:["Ofrecer una crema calmante.","Detener la venta y recomendar atención médica urgente.","Pedir que espere a ver si mejora."],correct:1,reason:"La dificultad respiratoria exige atención urgente. Una señal roja sin compromiso general también detiene la recomendación y puede requerir derivación."},
 c10:{prompt:"El envase destaca centella. ¿Cómo compruebas qué estás recomendando?",choices:["Asumir que la concentración es alta por estar en el frente.","Revisar INCI, etiqueta, función y fórmula completa.","Usar solo la historia tradicional como prueba."],correct:1,reason:"La cara frontal no prueba concentración ni eficacia. El INCI y la ficha vigente ayudan a poner el reclamo en contexto."},
 c11:{prompt:"Una crema se siente muy pesada y la clienta dejó de usarla. ¿Cuál es la siguiente pregunta?",choices:["¿Qué textura sí te resulta cómoda?","¿Quieres la misma crema en tamaño grande?","¿Por qué no la aplicas más cantidad?"],correct:0,reason:"Humectantes, emolientes y oclusivos cumplen funciones distintas. La textura y la adherencia importan en la elección."},
 c12:{prompt:"Una clienta lee 'centella' en un sérum. ¿Qué puedes afirmar?",choices:["Que cura la rosácea.","Que conviene revisar fórmula, uso y tolerancia antes de recomendarlo.","Que todos los extractos tienen la misma concentración."],correct:1,reason:"La historia tradicional y la investigación de compuestos no prueban el resultado de cualquier producto terminado."},
 c13:{prompt:"Una clienta tiene brillo, poros visibles y tirantez tras lavarse. ¿Por dónde comienzas?",choices:["Recomendar BHA, LHA y arcilla a diario.","Preguntar por su limpiador, hidratación y prioridad antes de añadir activos.","Asegurarle que un sérum cerrará sus poros."],correct:1,reason:"Brillo y tirantez pueden coexistir. Una rutina suave y tolerable permite observar mejor el problema principal sin sobrecargar la piel."},
 c14:{prompt:"Una clienta busca un sérum para manchas, pero una lesión nueva está cambiando de forma. ¿Qué haces?",choices:["Vender el producto más concentrado.","Derivar para evaluación antes de aconsejar un cosmético para esa lesión.","Recomendar dos exfoliantes para acelerar el cambio."],correct:1,reason:"Una lesión cambiante requiere evaluación. La asesoría cosmética puede continuar después con un objetivo y una rutina seguros."},
 c15:{prompt:"Una clienta nunca usó retinoides y pide el producto anti-aging más fuerte. ¿Qué haces?",choices:["Elegir el porcentaje más alto porque dará resultados más rápidos.","Preguntar objetivo, rutina y tolerancia; empezar por una opción que pueda sostener.","Sumar retinoide, ácidos y vitamina C desde el primer día."],correct:1,reason:"La potencia aislada no define una buena recomendación. La evidencia debe traducirse a una rutina tolerable, gradual y acompañada de fotoprotección."},
 c16:{prompt:"Una clienta usa retinol, BHA tres noches por semana y siente tirantez. Quiere sumar glicólico. ¿Qué haces?",choices:["Agregar glicólico una noche extra para acelerar.","Revisar la carga actual, reducir/espaciar y observar tolerancia antes de sumar.","Cambiar BHA por un scrub fuerte."],correct:1,reason:"La exfoliación se evalúa por carga total. Cuando ya existe tirantez, agregar intensidad puede empeorar tolerancia y dificultar saber qué producto causa el problema."},
 c17:{prompt:"Una clienta pide un sérum de exosomas porque vio que 'regenera la piel como un tratamiento clínico'. ¿Qué haces?",choices:["Confirmar que cualquier exosoma produce el mismo efecto.","Revisar fuente de las vesículas, INCI, vía estudiada y evidencia del producto antes de explicar beneficios.","Recomendar el producto más caro de la categoría."],correct:1,reason:"Exosomas y vesículas extracelulares pueden tener fuentes y vías distintas. El nombre comercial no demuestra equivalencia con un procedimiento clínico."},
 c18:{prompt:"Una clienta pregunta si debe dejar su niacinamida porque empezó vitamina C. ¿Qué haces?",choices:["Decir que se anulan y prohibir la combinación.","Revisar los productos concretos, la tolerancia y las instrucciones de marca antes de decidir.","Indicar que duplique ambos para compensar."],correct:1,reason:"Vitamina C y niacinamida no requieren una prohibición universal. Formulación y tolerancia importan más que una regla viral."},
 c19:{prompt:"Una clienta ya usa toner y serum hidratantes y pregunta qué essence necesita. ¿Qué haces?",choices:["Agregar una essence porque es el paso siguiente de K-Beauty.","Preguntar qué función nueva aportaría y evitar duplicar si no existe un gap.","Elegir la ampoule más concentrada."],correct:1,reason:"Toner, essence y serum pueden solaparse. El formato no justifica una capa si la función ya está cubierta."},
 c20:{prompt:"Una clienta que recién empieza quiere retinol, BHA, vitamina C y un sérum antimanchas desde el primer día. ¿Qué haces?",choices:["Armar los cuatro activos para que avance más rápido.","Construir base + una prioridad y agregar cambios de forma progresiva.","Eliminar moisturizer para reducir pasos."],correct:1,reason:"Una base estable y una prioridad permiten evaluar tolerancia y resultado. Introducir varios activos simultáneos aumenta complejidad y hace difícil identificar qué irrita."},
 c21:{prompt:"Una clienta pide un producto para poros. Ya usa BHA tres noches por semana y retinol otras tres. ¿Qué haces?",choices:["Agregar un AHA para completar la semana.","Auditar tolerancia, frecuencia y qué entiende por poros antes de sumar otro activo.","Elegir el serum viral con mejor reseña."],correct:1,reason:"El algoritmo revisa rutina actual y carga antes de buscar un producto nuevo. Puede descubrir que no existe un gap y que la mejor salida es ajustar, no sumar."},
 c22:{prompt:"Una clienta dice: quiero algo para mi piel. ¿Cuál es la mejor siguiente pregunta?",choices:["¿Cuánto quieres gastar?","De todo lo que te gustaría mejorar, ¿qué te preocupa más hoy?","¿Quieres el producto más vendido?"],correct:1,reason:"Una pregunta abierta y priorizada convierte una intención amplia en información útil sin empezar por producto ni precio."},
 c23:{prompt:"Una clienta dice que la opción recomendada está muy cara. ¿Qué haces primero?",choices:["Ofrecer descuento de inmediato.","Aclarar si la barrera es presupuesto o valor percibido antes de responder.","Mostrar cinco productos más."],correct:1,reason:"Una objeción debe entenderse antes de responder. Precio, valor, textura o timing requieren soluciones distintas."},
 c24:{prompt:"Una clienta pregunta para qué sirve una ampolla con niacinamida y TXA. ¿Cómo empiezas?",choices:["Leyendo todo el INCI.","Conectando su prioridad con el beneficio y luego explicando 1–3 ingredientes relevantes.","Prometiendo que borrará las manchas."],correct:1,reason:"El pitch empieza por relevancia para el cliente; los ingredientes respaldan la explicación y los límites evitan claims exagerados."},
 c25:{prompt:"Un cliente ya eligió un sérum antimanchas y no usa SPF. ¿Cuál es el cross-sell más coherente?",choices:["Otro sérum antimanchas.","Un protector solar compatible con sus preferencias.","Una mascarilla sólo porque está en promoción."],correct:1,reason:"La venta cruzada prioriza el paso que realmente falta. La relevancia va antes que margen, viralidad o cantidad de productos."},
 c26:{prompt:"Una clienta prueba por primera vez una ampolla disponible en 30 ml y 100 ml. El formato grande cuesta menos por ml. ¿Qué haces?",choices:["Recomendar 100 ml automáticamente.","Explicar la economía por ml, pero mantener 30 ml como opción válida si aún no sabe si la tolerará o usará.","Decir que el grande es mejor."],correct:1,reason:"El precio por ml ayuda a comparar, pero primera prueba, tolerancia, uso y presupuesto también forman parte de la decisión."},
 c27:{prompt:"Una clienta dice: está muy caro. ¿Cuál es la mejor primera respuesta?",choices:["Ofrecer descuento.","Preguntar si lo compara con otra opción, con su presupuesto o con el valor que percibe.","Defender el precio de inmediato."],correct:1,reason:"La frase no revela por sí sola la causa. Una pregunta de aclaración evita responder la objeción equivocada."},
 c28:{prompt:"Un SKU tiene 1.500 unidades en inventario. ¿Qué conclusión puedes sacar sólo con ese dato?",choices:["Está sobrestockeado.","Es best seller.","Sólo sé que hay profundidad de inventario; necesito ventas, cobertura, margen, rotación y rol."],correct:2,reason:"El inventario absoluto es una fotografía. Sin velocidad, cobertura, margen y contexto no permite concluir exceso ni éxito."},
 c29:{prompt:"Una tienda tiene 2 días de cobertura y otra 80 días del mismo SKU. ¿Qué revisas primero?",choices:["Comprar más para toda la red.","Transferir stock entre ubicaciones si la velocidad y costo lo justifican.","Aplicar descuento en ambas."],correct:1,reason:"Antes de recomprar, revisa si el inventario ya existe dentro de la red. La cobertura por ubicación puede revelar un problema de asignación, no de compra total."},
 c30:{prompt:"Un marketplace propone 20% de descuento. ¿Qué debes calcular antes de aprobar?",choices:["Sólo cuánto subirán las unidades.","Contribución después de descuento, comisión, logística y otros costos variables.","Sólo el precio de lista."],correct:1,reason:"Una campaña puede vender más y aun así destruir rentabilidad. La decisión correcta se toma sobre contribución post-canal."},
 c31:{prompt:"El equipo propone 30% off para todo el Cyber. ¿Cuál es la primera decisión correcta?",choices:["Subirlo a 40% para llamar más la atención.","Definir objetivo, elegibilidad, stock y margen antes del porcentaje.","Aplicarlo sólo a los productos más vendidos."],correct:1,reason:"La mecánica promocional viene después del objetivo y de la economía. Un descuento uniforme puede subsidiar demanda orgánica o provocar quiebres."},
 c32:{prompt:"Un producto tiene stock en la trastienda, pero su facing está vacío. ¿Qué problema tienes?",choices:["Compras insuficientes.","Reposición visual y ejecución de tienda.","Necesidad de descuento."],correct:1,reason:"Para el cliente, un facing vacío equivale a indisponibilidad aunque el sistema muestre stock. Primero corrige ejecución antes de recomprar o promocionar."},
 c33:{prompt:"El filtro “Rojeces” devuelve muy pocos productos. ¿Qué revisas primero?",choices:["El color del botón.","Los metacampos/tags y la taxonomía de catálogo.","El descuento."],correct:1,reason:"Filtros y búsqueda dependen de datos estructurados consistentes. Antes de rediseñar la interfaz, valida que el catálogo tenga la clasificación correcta."},
 c34:{prompt:"Un Reel educativo consigue muchos guardados pero pocas ventas directas. ¿Cómo lo evalúas?",choices:["Como fracaso automáticamente.","Contra su objetivo educativo: completion, saves y movimiento al siguiente paso.","Sólo por likes."],correct:1,reason:"Cada pieza necesita un KPI coherente con su trabajo. La conversión puede ocurrir después y por otro punto del recorrido."},
 c35:{prompt:"Un video retiene bien y genera muchos clics, pero la PDP convierte poco. ¿Qué revisas primero?",choices:["Regrabar sólo el hook.","PDP, precio, stock, variante y continuidad entre video y destino.","Cambiar la música."],correct:1,reason:"Si el video genera intención, la fricción puede estar después del clic. Diagnostica el embudo completo antes de culpar al creativo."}
};
export default function MiniDecision({chapterId}){
 const [choice,setChoice]=useState(null),item=cases[chapterId];if(!item)return null;
 return <section className="yeppo-mini-decision" aria-label="Decisión práctica"><small>DECISIÓN EN TIENDA · YEPPO</small><h3>{item.prompt}</h3><div>{item.choices.map((c,i)=><button type="button" key={i} className={choice===i?"selected":""} onClick={()=>setChoice(i)} aria-pressed={choice===i}>{c}</button>)}</div>{choice!==null&&<p role="status"><strong>{choice===item.correct?"Buen criterio.":"Revisa esta decisión."}</strong> {item.reason}</p>}</section>;
}
