// Fotografías documentales: créditos y enlaces en PHOTO-CREDITS.md.
const base="/assets/editorial/";
export const chapterEditorial={
 c01:{image:"portrait.jpg",alt:"Retrato editorial de una mujer",eyebrow:"El punto de partida",story:"La belleza coreana se volvió visible en todo el mundo a través de rutinas, formatos y una cultura de innovación. Su idea más útil para vender no es sumar pasos: es escuchar la piel y construir hábitos sostenibles.",tip:"En la primera conversación, pregunta qué producto usa hoy y qué espera mejorar. Recomienda un cambio fácil de evaluar."},
 c02:{image:"yeppo-centella.jpg",product:true,alt:"Madagascar Centella Ampoule de SKIN1004, producto del catálogo Yeppo",eyebrow:"Del interés a la recompra",story:"Una tendencia atrae visitas; una recomendación clara y disponibilidad constante convierten el interés en recompra. En Chile, la confianza también depende de información legible y una experiencia posventa seria.",tip:"Vende una solución concreta y explica cuándo volver a evaluar la rutina; evita prometer resultados en un plazo fijo."},
 c03:{image:"yeppo-spf.jpg",product:true,alt:"Relief Sun Rice + Probiotics de Beauty of Joseon, producto del catálogo Yeppo",eyebrow:"Una tienda con criterio",story:"La ventaja de una tienda especializada aparece cuando selección, asesoría y reposición cuentan la misma historia. La variedad sin orientación puede confundir más de lo que ayuda.",tip:"Si dos productos hacen lo mismo, explica la diferencia de textura, tolerancia y precio antes de ampliar el surtido."},
 c04:{image:"photo-4.jpg",alt:"Tratamiento facial en una cabina",eyebrow:"Entender antes de recomendar",story:"La superficie de la piel parece sencilla, pero su barrera combina células, lípidos y agua. La formación básica ayuda a interpretar lo que un cosmético puede hacer y dónde termina su alcance.",tip:"Relaciona una función de la piel con un beneficio cosmético específico; evita traducirlo en diagnóstico clínico."},
 c05:{image:"portrait.jpg",alt:"Retrato que muestra la diversidad de tipos de piel",eyebrow:"Más allá de una etiqueta",story:"Seca, grasa, mixta y normal sirven como guía inicial. La misma persona puede tener brillo y sentir tirantez; por eso el tipo habitual y el estado de hoy se preguntan por separado.",tip:"Pregunta cómo suele sentirse la piel y qué cambió esta semana. Son respuestas distintas y orientan la textura."},
 c06:{image:"yeppo-aloe.jpg",product:true,alt:"Aloe Hydro Formula de Holika Holika, producto del catálogo Yeppo",eyebrow:"La piel también cambia",story:"Clima, limpieza, productos nuevos y frecuencia de uso alteran la tolerancia. Una rutina corta puede dar mejor información que incorporar muchos activos al mismo tiempo.",tip:"Ante ardor persistente o empeoramiento, detén la recomendación de nuevos activos y sugiere evaluación profesional."},
 c07:{image:"photo-5.jpg",alt:"Fotografía de un tratamiento facial",eyebrow:"Elegir una prioridad",story:"Brotes, tono desigual, poros y textura son preocupaciones diferentes. Ponerles nombre permite decidir una meta a la vez y observar si la rutina ayuda.",tip:"Pide al cliente que elija una prioridad principal; así la recomendación sigue siendo medible y comprensible."},
 c08:{image:"hero-face.jpg",alt:"Retrato fotográfico en primer plano",eyebrow:"El límite también es servicio",story:"Observar y hacer preguntas ayuda a orientar una compra. Identificar una lesión, afirmar una causa médica o descartar riesgos exige otra formación y otro contexto.",tip:"Describe lo que la persona cuenta, sin etiquetar una enfermedad. Cuando la señal excede lo cosmético, deriva."},
 c09:{image:"photo-4.jpg",alt:"Fotografía de atención de la piel",eyebrow:"Saber cuándo detenerse",story:"Una buena venta también incluye reconocer señales que requieren atención profesional: dolor intenso, hinchazón, ampollas o empeoramiento rápido. La confianza se construye al priorizar a la persona.",tip:"Documenta el producto, el lote y la cronología si hay una reacción; no indiques continuar el uso para ‘acostumbrar’ la piel."},
 c10:{image:"centella.jpg",alt:"Hoja real de Centella asiatica",eyebrow:"Historias detrás del INCI",story:"La centella asiática, también llamada gotu kola, tiene usos tradicionales registrados en diversas regiones de Asia. Más tarde se estudiaron compuestos como asiaticósido y madecasósido. Esa trayectoria no convierte cualquier producto con centella en un tratamiento médico.",tip:"Busca Centella Asiatica Extract en el INCI y evalúa la fórmula completa. Un ingrediente destacado no revela su concentración ni eficacia por sí solo.",source:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/",sourceLabel:"Revisión científica · Centella asiatica in cosmetology"},
 c11:{image:"yeppo-cream.jpg",product:true,alt:"Centella Hydrating Serum de NIDA, producto del catálogo Yeppo",eyebrow:"Una fórmula, varias funciones",story:"Glicerina y otros humectantes ayudan a retener agua; emolientes aportan suavidad y oclusivos reducen la pérdida de agua. La combinación y la experiencia de uso importan más que un solo activo estrella.",tip:"Si la piel siente tirantez, compara humectación y textura. Para una barrera comprometida, una fórmula tolerable y simple puede ser mejor punto de partida."},
 c12:{image:"centella.jpg",alt:"Hoja real de Centella asiatica",eyebrow:"De la planta a la fórmula",story:"Centella, pantenol y otros ingredientes orientados al confort tienen historias y niveles de evidencia diferentes. Aprender a separarlos evita promesas que la fórmula no puede sostener.",tip:"Pregunta qué siente la persona y qué cambió recientemente; una fórmula calmante no reemplaza una evaluación profesional cuando hay señales intensas.",source:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/",sourceLabel:"Revisión científica · Centella asiatica in cosmetology"}
};
export function editorialFor(id){return chapterEditorial[id]||{image:"photo-0.jpg",alt:"Fotografía editorial de cosmética",eyebrow:"Aprender para asesorar",story:"Un capítulo para convertir conocimiento en una recomendación clara, responsable y útil para el cliente.",tip:"Parte de la necesidad del cliente antes de elegir el producto."}}
export function editorialImage(id){return base+editorialFor(id).image}
