// Fotografías documentales: créditos y enlaces en PHOTO-CREDITS.md.
const base="/assets/editorial/";
// Portadas con personas distintas. Las imágenes Pexels son fotografías editoriales;
// su ubicación no acredita nacionalidad ni vínculo con Yeppo.
const chapterCovers={
 c01:{image:"chile-model.jpg",alt:"Retrato editorial de una modelo en Santiago de Chile"},
 c02:{image:"https://images.pexels.com/photos/18460096/pexels-photo-18460096.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Modelo en un entorno urbano de Santiago de Chile"},
 c03:{image:"https://images.pexels.com/photos/11157339/pexels-photo-11157339.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Retrato editorial de una mujer con maquillaje contemporáneo"},
 c04:{image:"https://images.pexels.com/photos/2709386/pexels-photo-2709386.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Primer plano de piel real con pecas"},
 c05:{image:"chile-beauty.jpg",alt:"Retrato editorial de una mujer fotografiada en Santiago de Chile"},
 c06:{image:"https://images.pexels.com/photos/7608061/pexels-photo-7608061.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer aplicando crema en su rutina de cuidado"},
 c07:{image:"https://images.pexels.com/photos/5253959/pexels-photo-5253959.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Retrato de una mujer con pecas y textura natural de la piel"},
 c08:{image:"https://images.pexels.com/photos/4910150/pexels-photo-4910150.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer observando su rostro en un espejo"},
 c09:{image:"https://images.pexels.com/photos/17568374/pexels-photo-17568374.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Retrato editorial de una mujer en Santiago de Chile"},
 c10:{image:"https://images.pexels.com/photos/5709637/pexels-photo-5709637.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer leyendo la etiqueta de un cosmético en una tienda"},
 c11:{image:"https://images.pexels.com/photos/6925480/pexels-photo-6925480.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer aplicando hidratante en el rostro"},
 c12:{image:"https://images.pexels.com/photos/6543526/pexels-photo-6543526.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer aplicando crema con una brocha en el rostro"},
 c13:{image:"https://images.pexels.com/photos/5587981/pexels-photo-5587981.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Retrato editorial de una mujer con textura natural y brotes visibles"},
 c14:{image:"https://images.pexels.com/photos/7126382/pexels-photo-7126382.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Retrato editorial de una mujer con cabello rizado y maquillaje natural"},
 c15:{image:"https://images.pexels.com/photos/6724487/pexels-photo-6724487.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer adulta realizando una rutina de cuidado facial"},
 c16:{image:"https://images.pexels.com/photos/6476077/pexels-photo-6476077.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer aplicando sérum en una rutina de cuidado facial"},
 c17:{image:"https://images.pexels.com/photos/3764013/pexels-photo-3764013.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Retrato editorial de una mujer en una rutina contemporánea de cuidado facial"},
 c18:{image:"https://images.pexels.com/photos/6724357/pexels-photo-6724357.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer aplicando productos de skincare en una rutina por capas"},
 c19:{image:"https://images.pexels.com/photos/3373739/pexels-photo-3373739.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Selección editorial de productos de skincare y texturas"},
 c20:{image:"https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Mujer organizando una rutina cotidiana de cuidado facial"},
 c21:{image:"https://images.pexels.com/photos/3737594/pexels-photo-3737594.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Asesoría de cuidado facial con productos organizados para comparar opciones"},
 c22:{image:"https://images.pexels.com/photos/3768146/pexels-photo-3768146.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Conversación de asesoría entre una clienta y una especialista de belleza"},
 c23:{image:"https://images.pexels.com/photos/3764014/pexels-photo-3764014.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Asesora conversando con una clienta durante una recomendación de belleza"},
 c24:{image:"https://images.pexels.com/photos/3764015/pexels-photo-3764015.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Asesora explicando un producto de skincare durante una conversación de belleza"},
 c25:{image:"https://images.pexels.com/photos/3762876/pexels-photo-3762876.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Asesora de belleza mostrando productos complementarios a una clienta"},
 c26:{image:"https://images.pexels.com/photos/3762878/pexels-photo-3762878.jpeg?auto=compress&cs=tinysrgb&w=1100",alt:"Asesora comparando distintas opciones de producto con una clienta"}
};
export const chapterEditorial={
 c01:{image:"chile-model.jpg",alt:"Modelo fotografiada en Santiago de Chile",eyebrow:"El punto de partida",story:"La belleza coreana se volvió visible en todo el mundo a través de rutinas, formatos y una cultura de innovación. Su idea más útil para vender no es sumar pasos: es escuchar la piel y construir hábitos sostenibles.",tip:"En la primera conversación, pregunta qué producto usa hoy y qué espera mejorar. Recomienda un cambio fácil de evaluar."},
 c02:{image:"yeppo-centella.jpg",product:true,alt:"Madagascar Centella Ampoule de SKIN1004, producto del catálogo Yeppo",eyebrow:"Del interés a la recompra",story:"Una tendencia atrae visitas; una recomendación clara y disponibilidad constante convierten el interés en recompra. En Chile, la confianza también depende de información legible y una experiencia posventa seria.",tip:"Vende una solución concreta y explica cuándo volver a evaluar la rutina; evita prometer resultados en un plazo fijo."},
 c03:{image:"yeppo-spf.jpg",product:true,alt:"Relief Sun Rice + Probiotics de Beauty of Joseon, producto del catálogo Yeppo",eyebrow:"Una tienda con criterio",story:"La ventaja de una tienda especializada aparece cuando selección, asesoría y reposición cuentan la misma historia. La variedad sin orientación puede confundir más de lo que ayuda.",tip:"Si dos productos hacen lo mismo, explica la diferencia de textura, tolerancia y precio antes de ampliar el surtido."},
 c04:{image:"photo-4.jpg",alt:"Tratamiento facial en una cabina",eyebrow:"Entender antes de recomendar",story:"La superficie de la piel parece sencilla, pero su barrera combina células, lípidos y agua. La formación básica ayuda a interpretar lo que un cosmético puede hacer y dónde termina su alcance.",tip:"Relaciona una función de la piel con un beneficio cosmético específico; evita traducirlo en diagnóstico clínico."},
 c05:{image:"chile-beauty.jpg",alt:"Retrato editorial fotografiado en Santiago de Chile",eyebrow:"Más allá de una etiqueta",story:"Seca, grasa, mixta y normal sirven como guía inicial. La misma persona puede tener brillo y sentir tirantez; por eso el tipo habitual y el estado de hoy se preguntan por separado.",tip:"Pregunta cómo suele sentirse la piel y qué cambió esta semana. Son respuestas distintas y orientan la textura."},
 c06:{image:"yeppo-aloe.jpg",product:true,alt:"Aloe Hydro Formula de Holika Holika, producto del catálogo Yeppo",eyebrow:"La piel también cambia",story:"Clima, limpieza, productos nuevos y frecuencia de uso alteran la tolerancia. Una rutina corta puede dar mejor información que incorporar muchos activos al mismo tiempo.",tip:"Ante ardor persistente o empeoramiento, detén la recomendación de nuevos activos y sugiere evaluación profesional."},
 c07:{image:"photo-5.jpg",alt:"Fotografía de un tratamiento facial",eyebrow:"Elegir una prioridad",story:"Brotes, tono desigual, poros y textura son preocupaciones diferentes. Ponerles nombre permite decidir una meta a la vez y observar si la rutina ayuda.",tip:"Pide al cliente que elija una prioridad principal; así la recomendación sigue siendo medible y comprensible."},
 c08:{image:"chile-portrait.jpg",alt:"Modelo fotografiada en Santiago de Chile",eyebrow:"El límite también es servicio",story:"Observar y hacer preguntas ayuda a orientar una compra. Identificar una lesión, afirmar una causa médica o descartar riesgos exige otra formación y otro contexto.",tip:"Describe lo que la persona cuenta, sin etiquetar una enfermedad. Cuando la señal excede lo cosmético, deriva."},
 c09:{image:"photo-4.jpg",alt:"Fotografía de atención de la piel",eyebrow:"Saber cuándo detenerse",story:"Una buena venta también incluye reconocer señales que requieren atención profesional: dolor intenso, hinchazón, ampollas o empeoramiento rápido. La confianza se construye al priorizar a la persona.",tip:"Documenta el producto, el lote y la cronología si hay una reacción; no indiques continuar el uso para ‘acostumbrar’ la piel."},
 c10:{image:"yeppo-centella.jpg",product:true,alt:"Madagascar Centella Ampoule de SKIN1004, producto del catálogo Yeppo",eyebrow:"Historias detrás del INCI",story:"La centella asiática, también llamada gotu kola, tiene usos tradicionales registrados en diversas regiones de Asia. Más tarde se estudiaron compuestos como asiaticósido y madecasósido. Esa trayectoria no convierte cualquier producto con centella en un tratamiento médico.",tip:"Busca Centella Asiatica Extract en el INCI y evalúa la fórmula completa. Un ingrediente destacado no revela su concentración ni eficacia por sí solo.",source:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/",sourceLabel:"Revisión científica · Centella asiatica in cosmetology"},
 c11:{image:"yeppo-cream.jpg",product:true,alt:"Centella Hydrating Serum de NIDA, producto del catálogo Yeppo",eyebrow:"Una fórmula, varias funciones",story:"Glicerina y otros humectantes ayudan a retener agua; emolientes aportan suavidad y oclusivos reducen la pérdida de agua. La combinación y la experiencia de uso importan más que un solo activo estrella.",tip:"Si la piel siente tirantez, compara humectación y textura. Para una barrera comprometida, una fórmula tolerable y simple puede ser mejor punto de partida."},
 c12:{image:"yeppo-centella.jpg",product:true,alt:"Madagascar Centella Ampoule de SKIN1004, producto del catálogo Yeppo",eyebrow:"De la planta a la fórmula",story:"Centella, pantenol y otros ingredientes orientados al confort tienen historias y niveles de evidencia diferentes. Aprender a separarlos evita promesas que la fórmula no puede sostener.",tip:"Pregunta qué siente la persona y qué cambió recientemente; una fórmula calmante no reemplaza una evaluación profesional cuando hay señales intensas.",source:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3834700/",sourceLabel:"Revisión científica · Centella asiatica in cosmetology"},
 c13:{image:"https://yeppo.cl/cdn/shop/files/Purito-0341_700x700.jpg?v=1784058456",product:true,alt:"Purito Azelaic Acid 10 Kojic Tea Tree Serum, producto del catálogo Yeppo",eyebrow:"Una decisión por vez",story:"El brillo, la apariencia de los poros y los brotes requieren preguntas diferentes. Una rutina de pocos pasos permite evaluar tolerancia; una lesión profunda o dolorosa necesita evaluación dermatológica.",tip:"Pregunta por limpiador, hidratación y activos actuales antes de sumar exfoliación. No prometas cerrar poros ni tratar acné con un cosmético.",source:"https://www.aad.org/public/everyday-care/skin-care-secrets/face/treat-large-pores",sourceLabel:"AAD · apariencia de poros"},
 c14:{image:"https://yeppo.cl/cdn/shop/files/celimax-pore-dark-spot-brightening-serum-30ml-product_c698b620-87e8-41e8-bd62-3b48e5a8d6d2_640x640.png?v=1779802501",product:true,alt:"Celimax Pore + Dark Spot Brightening Serum, producto del catálogo Yeppo",eyebrow:"La claridad empieza por la pregunta",story:"Una marca posterior a un brote, un tono apagado y una mancha cambiante necesitan respuestas distintas. La fotoprotección y la tolerancia sostienen cualquier conversación cosmética sobre luminosidad.",tip:"Pregunta cuándo apareció, qué usa actualmente y si alguna fórmula causa ardor. Una lesión cambiante se deriva.",source:"https://www.aad.org/public/everyday-care/skin-care-secrets/routine/fade-dark-spots",sourceLabel:"AAD · cuidado de manchas"},
 c15:{image:"https://yeppo.cl/cdn/shop/products/CosRX-The-Retinol-0.1-cream-01_700x700.jpg?v=1705408278",product:true,alt:"COSRX The Retinol 0.1 Cream, producto del catálogo Yeppo",eyebrow:"Más evidencia, menos promesas",story:"Anti-aging no significa detener el tiempo. La diferencia está en separar prevención, tratamiento cosmético y tendencias, y elegir una rutina que la persona pueda sostener sin irritarse.",tip:"Antes de hablar de potencia, pregunta qué signo quiere mejorar, qué activos usa hoy y cómo tolera su piel.",source:"https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/selecting-anti-aging-products",sourceLabel:"AAD · selección de productos anti-aging"},
 c16:{image:"https://cdn.shopify.com/s/files/1/0638/7348/2901/products/Tiam-AC-Fighting-AHA-BHA-Toner-01.jpg?v=1705401551",product:true,alt:"TIAM AC Fighting AHA BHA PHA Toner, producto del catálogo Yeppo",eyebrow:"Más ácido no es más criterio",story:"Exfoliar puede mejorar textura y obstrucción, pero la dosis acumulada importa tanto como la familia del ingrediente. La mejor rutina usa la mínima intensidad que logra el objetivo sin deteriorar tolerancia.",tip:"Pregunta qué exfoliantes, retinoides y tratamientos ya usa la persona antes de sumar otro ácido.",source:"https://www.aad.org/public/everyday-care/skin-care-secrets/routine/safely-exfoliate-at-home",sourceLabel:"AAD · exfoliación segura"},
 c17:{image:"https://yeppo.cl/cdn/shop/files/Medicube-0081_700x700.jpg?v=1760367189",product:true,alt:"Medicube Exosome Shot Pore Serum 2000, producto del catálogo Yeppo",eyebrow:"Innovación con evidencia en contexto",story:"PDRN, exosomas, spicules y NAD+ pueden partir de biología real y aun así llegar al mercado con claims que van más lejos que los estudios. El criterio está en reconocer dónde termina la evidencia y dónde empieza la extrapolación.",tip:"Cuando un ingrediente se vuelve viral, pide tres datos antes de venderlo: fuente exacta, vía estudiada y evidencia de la fórmula concreta.",source:"https://pubmed.ncbi.nlm.nih.gov/42411735/",sourceLabel:"2026 · evidencia clínica de exosomas tópicos"},
 c18:{image:"https://yeppo.cl/cdn/shop/products/CosRX-The-Retinol-0.1-cream-01_700x700.jpg?v=1705408278",product:true,alt:"COSRX The Retinol 0.1 Cream, producto del catálogo Yeppo",eyebrow:"Compatibilidad no es una tabla de prohibiciones",story:"Dos activos pueden ser químicamente compatibles y aun así resultar demasiado intensos juntos. La decisión correcta combina formulación, instrucciones del fabricante, tolerancia y contexto de la rutina.",tip:"Antes de separar dos ingredientes, identifica si el problema real es estabilidad, irritación o simplemente exceso de productos.",source:"https://www.aad.org/public/everyday-care/skin-care-basics/care/apply-skin-care-certain-order",sourceLabel:"AAD · orden y carga de productos"},
 c19:{image:"https://yeppo.cl/cdn/shop/files/RoundLab-Ampoule-1_700x700.jpg",product:true,alt:"Round Lab 1025 Dokdo Ampoule, producto del catálogo Yeppo",eyebrow:"Formato no es función",story:"K-Beauty usa una gran variedad de nombres y texturas. La diferencia entre una buena asesoría y una rutina inflada está en saber qué función aporta cada capa.",tip:"Antes de recomendar toner, essence, serum o ampoule, pregunta qué problema resuelve esa capa que la rutina todavía no cubre.",source:"https://www.aad.org/public/everyday-care/skin-care-basics/care/apply-skin-care-certain-order",sourceLabel:"AAD · arquitectura básica de rutina"},
 c20:{image:"https://yeppo.cl/cdn/shop/files/iunik-Sunscreen-1_700x700.jpg",product:true,alt:"iUNIK Centella Calming Daily Sunscreen, producto del catálogo Yeppo",eyebrow:"Una rutina debe poder sostenerse",story:"La arquitectura correcta empieza por base y prioridad. Los productos opcionales entran después, cuando existe tolerancia y una función concreta que todavía no está cubierta.",tip:"Pregunta qué usa hoy, qué quiere mejorar primero y qué paso está dispuesto a repetir todos los días.",source:"https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-budget",sourceLabel:"AAD · rutina simple y sostenible"},
 c21:{image:"https://yeppo.cl/cdn/shop/files/iunik-Sunscreen-1_700x700.jpg",product:true,alt:"iUNIK Centella Calming Daily Sunscreen, ejemplo del catálogo Yeppo",eyebrow:"Recomendar es decidir y explicar",story:"El algoritmo Yeppo parte de seguridad y necesidad, audita la rutina actual, compara pocas opciones y entrega instrucciones que el cliente puede ejecutar. Su valor no es automatizar personas: es hacer consistente el criterio.",tip:"Si no puedes explicar qué dato hizo ganar a un producto, todavía no terminaste la recomendación.",source:"https://www.aad.org/public/everyday-care/skin-care-basics/care/apply-skin-care-certain-order",sourceLabel:"AAD · menos productos, mejor uso"},
 c22:{image:"https://yeppo.cl/cdn/shop/files/RoundLab-Dokdo-Toner-01_700x700.jpg",product:true,alt:"Round Lab 1025 Dokdo Toner, ejemplo del catálogo Yeppo",eyebrow:"Preguntar antes de mostrar producto",story:"Una entrevista breve y bien guiada reduce recomendaciones genéricas. La asesora descubre prioridad, rutina, tolerancia y preferencias, resume lo entendido y recién entonces conecta la necesidad con el catálogo.",tip:"No encadenes preguntas sin contexto. Explica por qué preguntas y confirma lo que entendiste antes de recomendar.",source:"https://blog.hubspot.com/sales/consultative-selling",sourceLabel:"HubSpot · venta consultiva y escucha activa"},
 c23:{image:"https://yeppo.cl/cdn/shop/files/iunik-Sunscreen-1_700x700.jpg",product:true,alt:"iUNIK Centella Calming Daily Sunscreen, producto del catálogo Yeppo",eyebrow:"Vender criterio, no cantidad",story:"La venta consultiva toma lo que el cliente dijo, reduce opciones, explica diferencias reales y deja una decisión fácil de entender. Después acompaña el uso y la recompra.",tip:"Si una objeción aparece, entiende primero qué significa. No respondas precio, textura o miedo a irritación con la misma solución.",source:"https://www.salesforce.com/blog/sales/spin-selling/",sourceLabel:"Salesforce · SPIN Selling 2026"},
 c24:{image:"https://yeppo.cl/cdn/shop/files/SKIN1004-Tone-Brightening-Capsule-Ampoule-01_700x700.jpg",product:true,alt:"SKIN1004 Madagascar Centella Tone Brightening Capsule Ampoule, producto del catálogo Yeppo",eyebrow:"Explicar sin deformar",story:"Un buen pitch parte de la necesidad, traduce el beneficio, selecciona evidencia relevante, aterriza sensorialidad y uso, y deja claro qué puede esperar el cliente sin convertir un cosmético en una promesa médica.",tip:"Si el cliente entiende para qué sirve, cómo se usa y qué no promete, la explicación ya está haciendo su trabajo.",source:"https://www.sernac.cl/604/w3-article-78768.html",sourceLabel:"SERNAC · respaldo de promesas cosméticas"},
 c25:{image:"https://yeppo.cl/cdn/shop/files/iunik-Sunscreen-1_700x700.jpg",product:true,alt:"Protector solar iUNIK del catálogo Yeppo como ejemplo de complemento relevante",eyebrow:"Completar, no inflar",story:"El cross-selling consultivo parte del producto ancla y pregunta qué función falta realmente. Relevancia, margen y recompra se miden juntos; una canasta mayor no es mejor si el cliente no entiende para qué sirve cada paso.",tip:"Antes de agregar un SKU, pregunta: ¿cubre un gap real, mejora uso o sólo aumenta ticket?",source:"https://baymard.com/guidelines/813-cross-sell-product-relevance",sourceLabel:"Baymard · relevancia de cross-sells, actualizado 2026"},
 c26:{image:"https://yeppo.cl/cdn/shop/files/SKIN1004-Tone-Brightening-Capsule-Ampoule-01_700x700.jpg",product:true,alt:"Ampolla SKIN1004 usada como ejemplo de comparación de formatos y valor",eyebrow:"Más caro sólo si aporta más valor",story:"El upselling consultivo valida la opción base, identifica una mejora concreta y devuelve el control al cliente. El formato grande, la fórmula más compleja o una mayor intensidad sólo tienen sentido cuando encajan con uso, tolerancia y presupuesto.",tip:"Antes de ofrecer un upgrade, responde tres cosas: qué cambia, para quién mejora y cuándo no lo ofrecerías.",source:"https://www.sernac.cl/portal/618/w3-article-88176.html",sourceLabel:"SERNAC · reglamento PPUM, 2026"}
};
export function editorialFor(id){return chapterEditorial[id]||{image:"photo-0.jpg",alt:"Fotografía editorial de cosmética",eyebrow:"Aprender para asesorar",story:"Un capítulo para convertir conocimiento en una recomendación clara, responsable y útil para el cliente.",tip:"Parte de la necesidad del cliente antes de elegir el producto."}}
export function editorialImage(id){const image=editorialFor(id).image;return image.startsWith("http")?image:base+image}
export function editorialCover(id){const cover=chapterCovers[id]||chapterCovers.c01;return {...cover,src:cover.image.startsWith("http")?cover.image:base+cover.image}}
